### ISSUE TITLE
Code block missing in online doc

### ISSUE THREAD

**Issue by CharlyCast** [hsahovic/poke-env#1]
In "Getting Started" under "installing poke-env" the code block 

```python
pip install poke-env
```

Is not visible. Other blocks appears on the same page, and when building the doc locally I do get the pip install block. Any configuration issue?

![poke-env-doc](https://user-images.githubusercontent.com/23420125/68577832-2235fb00-0471-11ea-91ff-6695c2e90a8d.png)

---

EDIT:

After comparing the online doc with the one I built locally, I seems that many more code blocks are missing, for instance the instructions on how to setup a local showdown server:

### Online documentation:

![setup-live](https://user-images.githubusercontent.com/23420125/68578595-9a50f080-0472-11ea-805c-d51389ec4ab0.png)

### My locally build documentation

![setup-perso](https://user-images.githubusercontent.com/23420125/68578601-9c1ab400-0472-11ea-9896-3b312c23cdbe.png)

**Comment by hsahovic** [comment]
Thank you for bringing that up.

I'll investigate an correct that asap.

**Comment by hsahovic** [comment]
Fixed in #2.
