### ISSUE TITLE
double_battle.available_moves

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#101]
double_battle.available_moves doesn't return struggle in cases where a choice-item locked pokemon runs out of PP

**Comment by hsahovic** [comment]
Hi @caymansimpson,

Thanks for opening this issue. I'll try to get a fix this week :)

**Comment by hsahovic** [comment]
Hey @caymansimpson,

I've haven't been able to reproduce this issue. In doubles, I've pitted two `RandomPlayer`s, both using the following team:

```
Magikarp  
Ability: Swift Swim  
EVs: 252 Spe  
Jolly Nature  
IVs: 0 Atk  
- Splash  

Azurill @ Choice Band  
Ability: Thick Fat  
EVs: 252 Spe  
Jolly Nature  
IVs: 0 Atk  
- Rain Dance  
- Protect 
```
I displayed `battle.available_moves` for each move choice. I do see struggle popping up (printing `battle.available_moves` displays `[[splash (Move object)], [struggle (Move object)]]`) when the pp are out, and the battle finishes as expected without any error-ish display.

Do you have an idea for reproducing the issue you encountered with a minimal example?

**Comment by hsahovic** [comment]
Closing this for now - feel free to reopen it if you have a snippet to reproduce it :)
