### ISSUE TITLE
Error connecting agent to showdown server

### ISSUE THREAD

**Issue by Auxowave** [hsahovic/poke-env#105]
Hi, when I try to connect my player to the online pokemon showdown server I get the following error:

"""
2020-12-16 16:53:24,751 - Auxobot - CRITICAL - Unhandled message: |queryresponse|debug|true

2020-12-16 16:53:24,752 - Auxobot - ERROR - Unhandled exception raised while handling message:
|queryresponse|debug|true
Traceback (most recent call last):
  File "C:\XXXX\XXXX\XXXX\XXXX\XXXX\Python\Python39\lib\site-packages\poke_env\player\player_network_interface.py", line 165, in _handle_message
    raise NotImplementedError("Unhandled message: %s" % message)
NotImplementedError: Unhandled message: |queryresponse|debug|true
"""

The RandomPlayer I'm trying to connect is using server_configuration = ShowdownServerConfiguration
It works just fine using the default configuration when running a local version of showdown. It just doesn't work with the online showdown server. I've also tried just running the exact code example you've got for connecting your agent to showdown, obviously using my bots login info etc., but that gave the same error.
I think it worked like when I tried it like a week ago, but that might just be me misremembering and actually having it working on my locally hosted showdown. But it also might just be something wrong on pokemon showdown's side.
Otherwise, any idea what could be the cause?

**Comment by hsahovic** [comment]
Hey @Auxowave,

Thanks for opening this issue. I'll look into this tonight and push a fix asap.

**Comment by hsahovic** [comment]
This should be fixed by #105. I'll release `0.4.4`, with the fix, later tonight.

**Comment by Auxowave** [comment]
Awesome

**Comment by hsahovic** [comment]
Done! `pip install poke-env==0.4.4` should do the trick :)
