### ISSUE TITLE
gen5 support

### ISSUE THREAD

**Issue by awx1** [hsahovic/poke-env#107]
Could you add support for gen5, I'm interested in applying reinforcement learning to specifically gen5 random battles!

**Comment by hsahovic** [comment]
Hey @awx1,

I'll look into it sometime this week - depending on how it goes I might add gen 5 support.

**Comment by hsahovic** [comment]
@awx1 I took a first look at it yesterday - it looks like it should be doable without too much effort. I'll try to get gen 5 (as well as gen 4 and 6) support out sometime this week.

**Comment by hsahovic** [comment]
Version `0.4.5` is out with preliminary gen 4, 5 and 6 support.
The current test coverage only accounts for random battles. This has been done quite quickly, so things might go sour - if you encounter a problem with these formats don't hesitate to open a new issue!
