### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by bubloo7** [hsahovic/poke-env#108]
Is it possible to turn on timer? When my bot plays on the ladder, my opponent sometimes just leaves.

**Comment by hsahovic** [comment]
Hey @bubloo7,

Yes, I was planning on doing like that - I'll try to get it out this week.

**Comment by bubloo7** [comment]
okay thank you!

**Comment by hsahovic** [comment]
@bubloo7 version `0.4.6` adds an utility to request the timer at the start of each battle.
You just need to `pip install poke-env==0.4.6` and set `start_timer_on_battle_start` to `True` when creating `Player` objects (or `Player` child classes objects).

**Comment by bubloo7** [comment]
Works great. Thank you!
