### ISSUE TITLE
Strange bug that occurs very rarely

### ISSUE THREAD

**Issue by henrycharlesworth** [hsahovic/poke-env#11]
I haven't really figured out what's causing this, but every now and then (like every 100 battles or so on average) there's a situation where the pokemon has more than 4 moves when you call pokemon.moves. In the example I've just found, I have a dragonite with no item that has "roost", "dragondance", "earthquake", "outrage" and somehow "zdragondance" in its moves (it doesn't appear in battle.available_moves, I just noticed it because my neural network input is built assuming that the pokemon has at most 4 moves). It also correctly doesn't appear in available_z_moves, so it's pretty odd! Will let you know if I can track down in more detail why this is arising, but thought I would report it anyway!

**Comment by hsahovic** [comment]
Thanks for your report. I will try to find where this is coming from.

Do you have a minimal example where it occurs?

**Comment by henrycharlesworth** [comment]
So running the following you should find the error:

`import asyncio
from poke_env.player.player import Player
from poke_env.player.random_player import RandomPlayer
from poke_env.environment.battle import Battle
from poke_env.player_configuration import PlayerConfiguration
from poke_env.server_configuration import LocalhostServerConfiguration
from poke_env.player.utils import cross_evaluate

class TestPlayer(Player):
    def choose_move(self, battle) -> str:
        if len(battle.active_pokemon.moves.values()) > 4 or len(battle.opponent_active_pokemon.moves.values()) > 4:
            print("too many moves!")
        return self.choose_random_move(battle)

async def main():
    player_1_configuration = PlayerConfiguration("P1", None)
    player_2_configuration = PlayerConfiguration("P2", None)
    p1 = TestPlayer(
        player_configuration=player_1_configuration,
        battle_format="gen7randombattle",
        server_configuration=LocalhostServerConfiguration
    )
    p2 = TestPlayer(
        player_configuration=player_2_configuration,
        battle_format="gen7randombattle",
        server_configuration=LocalhostServerConfiguration
    )

    cross_evaluation = await cross_evaluate(
        [p1, p2], n_challenges=1000
    )
    print("done")

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())`

**Comment by hsahovic** [comment]
I am currently investigating.

The problem seems to be linked to z-moves being invalidly stored. I am implementing a fix, and should release it tonight if no other underlying issue is discovered.

**Comment by hsahovic** [comment]
It seems that Zoroark's illusions can also cause some trouble.

I will implement a temporary fix to prevent pokemons from registering more than 4 moves. A deep dive into illusion mechanics is also added to my backlog.

**Comment by hsahovic** [comment]
This issue should be solved in version 0.0.4. You can update your package to get the fix :)

**Comment by henrycharlesworth** [comment]
Awesome, thanks for such a quick response!
