### ISSUE TITLE
Hazard layer amount

### ISSUE THREAD

**Issue by mancho1987** [hsahovic/poke-env#110]
Hi,

How can I get the number of layers of each specific entry hazard?

**Comment by hsahovic** [comment]
Hi @mancho1987,

Thanks for opening this issue. Right now, this is not implemented.
I will take a look at some relevant battle logs sometime this week and get back to you.

**Comment by mancho1987** [comment]
Great, thanks :) 
Also, is there a way to get if the mon is locked into a move like outrage?

**Comment by hsahovic** [comment]
If your pokemon is locked into a move, `Battle.available_switches` will be empty and `Battle.available_moves` will only contain one move. Additionally, if showdown indicates that your pokemon is trapped, `Battle.trapped` will be `True`.

**Comment by hsahovic** [comment]
Version `0.4.7` takes care of counting `SideCondition`, which includes spikes, toxic spikes, and other similar moves.

Before `0.4.7`, `Battle.side_conditions` and `Battle.opponent_side_conditions` were `set`s of `SideCondition` objects. Now, they are `dict`s whose values correspond to the number of layers in place. For instance, you can now use `battle.opponent_side_conditions.get(SideCondition.SPIKES, 0)` to get the number of spikes layers on your opponent's side of the battle
