### ISSUE TITLE
Disabled Moves

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#111]
Is there a way to understand whether a move is disabled (like through disable or taunt)? Obviously low priority to support since these are situational - but these would definitely help limit exploration/problem space!

**Comment by hsahovic** [comment]
Hi @caymansimpson,

The `Battle` object has an `available_moves` property, which does not contain moves that are flagged as disabled by showdown. I believe this flag factors, among other things, both disable and taunt.
