### ISSUE TITLE
Websockets Connection Closed Error 

### ISSUE THREAD

**Issue by bubloo7** [hsahovic/poke-env#114]
I keep getting the following error when I run the bot for long periods of time on the official showdown website.
`websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason`
I googled the issue and found [this](https://stackoverflow.com/questions/54101923/1006-connection-closed-abnormally-error-with-python-3-7-websockets) and was wondering if you could implement this solution?

**Comment by bubloo7** [comment]
sorry I made a mistake in my code oops

**Comment by hsahovic** [comment]
Out of curiosity, what was the error that caused this?

**Comment by bubloo7** [comment]
I think it kept spamming the server with illegal moves like switching to a pokemon that was already dead which made the WebSocket close.
