### ISSUE TITLE
Question: Reward Buffer

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#115]
Sorry for all the questions - let me know if there's a better forum to raise these!

What's the point of self._reward_buffer? https://github.com/hsahovic/poke-env/blob/f16d70e8b80e2c880170730d9b6ef9c61c2b6bf2/src/poke_env/player/env_player.py#L236-L263

It seems like self._reward_buffer's only purpose (when starting_value=0) is to disincentivize visiting the same state again (by setting the reward to 0 if you've already visited the same state) - or am I missing something? (ie is there some other use of it w/in Gym)?

**Comment by hsahovic** [comment]
Hey @caymansimpson,

No problem with questions - they are welcome :)
The `reward_computing_helper` method's goal is to compute a reward for the last action you took. To do so, it scores the state of the battle and compares that score with the score of the previous state: the reward is the difference between these scores. Therefore, if your last action made the state better, it will have a positive reward; if it made it worse, it will have a negative reward.

The `_reward_buffer` attributes stores the score of the previous state per battle.
