### ISSUE TITLE
Team Preview for VGC

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#116]
First, thank you for all the documentation, especially [here](https://poke-env.readthedocs.io/en/stable/ou_max_player.html)! 
How does `teampreview()` operate in doubles (specifically VGC, when we're supposed to return only 4 out of the 6 mons)? I copied your `MaxDamagePlayer` and [adapted it to VGC](https://github.com/caymansimpson/reuniclusVGC/blob/main/bots/max_damage_player.py#L89-L104). However, I'm not able to get results that I expect

What battle.team returns:
```
p2: Zapdos
p2: Dragapult
p2: Swampert
p2: Clefairy
p2: Celesteela
p2: Rotom
```
What I'm returning in `teampreview()`: `/team 352461`

What I would expect to happen: `Rotom` & `Swampert` lead, with `Zapdos` and `Celesteela` in back
What actually happens: `Rotom` & `Swampert` lead, with `Dragapult` and `Clefairy` in back

**Comment by hsahovic** [comment]
Looking at [smogon's simulator protocol](https://github.com/smogon/pokemon-showdown/blob/master/sim/SIM-PROTOCOL.md#possible-choices), I would try restricting your choice to only four pokemons ie. `/team 3524`.

I would expect `3524` to result in a Swampert / Celesteela lead with Dragapult and Clefairy in the back. If the issue persists when choosing four pokemons, please let me know and if possible include a minimal example to reproduce the issue :)

**Comment by caymansimpson** [comment]
That works - your intuition is right!
