### ISSUE TITLE
Protect

### ISSUE THREAD

**Issue by mancho1987** [hsahovic/poke-env#117]
Hi, 

Is there a way for the agent to know if it used protect in the previous turn, so it learns to not use it many times in a row? Also for moves like first impression and fakeout.

Thanks!

**Comment by hsahovic** [comment]
Hi @mancho1987,

Thanks for opening this issue.
These and a couple of other related features are planned in my next series of `poke-env` update, adapted from work done by @dmizr on his fork. I'm not sure when it will be released fully - probably sometime in the next two weeks? If one of these is a priority on your end, I can try to get it out first.

Best,
Haris

**Comment by mancho1987** [comment]
Awesome! If protect and max guard could be first I will appreciate it a lot.

**Comment by hsahovic** [comment]
Hey @mancho1987; this should be introduced in #121 along a couple of similar changes. I'll try to release it during the weekend :)

**Comment by hsahovic** [comment]
This is now merged and available in version `0.4.8` :)
