### ISSUE TITLE
Potential Parsing issue for VGC

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#120]
Hey @hsahovic - I'm reformatting my work to build off your implementation of BattleOrder (link to [my fork](https://github.com/caymansimpson/poke-env/blob/master/src/poke_env/environment/double_battle.py)). The issue seems to be coming from 
> |-damage|p2a: Porygon2|24/48g <- note the g

Is this expected?

```
2021-01-22 17:06:14,246 - SmarterRandomPlayer 1 - ERROR - Unhandled exception raised while handling message:
>battle-gen8vgc2021-30651
|
|t:|1611363974
|switch|p2b: Regieleki|Regieleki, L50|48/48
|-start|p1b: Swampert|Dynamax
|-heal|p1b: Swampert|414/414|[silent]
|move|p1a: Landorus|Fly||[still]
|-prepare|p1a: Landorus|Fly
|move|p1b: Swampert|Max Quake|p2a: Porygon2
|-damage|p2a: Porygon2|24/48g
|-boost|p1a: Landorus|spd|1
|-boost|p1b: Swampert|spd|1
|-damage|p1b: Swampert|394/414|[from] item: Life Orb
|move|p2a: Porygon2|Trick Room|p2a: Porygon2
|-fieldstart|move: Trick Room|[of] p2a: Porygon2
|
|upkeep
|turn|2
```

Here's the trace:
```
Traceback (most recent call last):
  File "/Users/cayman/Repositories/poke-env/src/poke_env/player/player_network_interface.py", line 131, in _handle_message
    await self._handle_battle_message(split_messages)
  File "/Users/cayman/Repositories/poke-env/src/poke_env/player/player.py", line 297, in _handle_battle_message
    battle._parse_message(split_message)
  File "/Users/cayman/Repositories/poke-env/src/poke_env/environment/abstract_battle.py", line 256, in _parse_message
    self.get_pokemon(pokemon)._damage(hp_status)
  File "/Users/cayman/Repositories/poke-env/src/poke_env/environment/pokemon.py", line 158, in _damage
    self._set_hp_status(hp_status)
  File "/Users/cayman/Repositories/poke-env/src/poke_env/environment/pokemon.py", line 232, in _set_hp_status
    self._max_hp = int(self._max_hp)
ValueError: invalid literal for int() with base 10: '48g'
```

**Comment by hsahovic** [comment]
Hey @caymansimpson,

Thanks for opening this issue. I've never seen this `g` before; which version of showdown are you using? Do you know if it has a special meaning?

**Comment by caymansimpson** [comment]
I'm using the same version as in your fork - I'll dive a bit deeper because this is pretty peculiar

**Comment by hsahovic** [comment]
Is this happening systematically (eg. easy to reproduce?) or is it a one-time thing?

**Comment by caymansimpson** [comment]
I've put in a patch to fix it (remove the last character of the HP string if it can't be coerced to an int) to unblock myself - but this is fairly reproducible - it looks to trigger when I use the move Whirlpool.

**Comment by hsahovic** [comment]
This should be fixed in [this commit](https://github.com/hsahovic/poke-env/commit/1e7ac23619ebd869d47862a1b9edd12525eabdac); I am currently planning on releasing it with #121 when these changes are merged. I can release it earlier if you prefer to use the `pip` package instead of master / your fork.
Let me know what works best for you!

**Comment by caymansimpson** [comment]
Do whatever's easiest for you - I'll update accordingly! Thanks for being so on top of these
