### ISSUE TITLE
Showdown team parser doesn't support gmax syntax

### ISSUE THREAD

**Issue by darrenswhite** [hsahovic/poke-env#124]
**Summary**:
When using `Teambuilder#parse_showdown_team`, the nickname will be parsed incorrectly when parsing a gmax pokemon.

**Actual outcome**:
Nickname will be parsed as "Gigantamax: Yes".

**Expected outcome**
Nickname parsed as "Coalossal". Potentially a gmax flag set as True/False/None.

**Example**:
```
Coalossal @ Weakness Policy  
Ability: Steam Engine  
Level: 50  
Gigantamax: Yes  
EVs: 252 HP / 252 SpA / 4 SpD  
Modest Nature  
IVs: 0 Atk  
- Heat Wave  
- Meteor Beam  
- Protect  
- Solar Beam  
```

**Comment by hsahovic** [comment]
Hey @darrenswhite,

Thanks for opening this issue, that's a good catch. I'll try to get a fix out tonight.

**Comment by darrenswhite** [comment]
> Hey @darrenswhite,
> 
> Thanks for opening this issue, that's a good catch. I'll try to get a fix out tonight.

Thanks @hsahovic . If you're busy I can always create a PR :)

**Comment by hsahovic** [comment]
> Thanks @hsahovic . If you're busy I can always create a PR :)

Up to you! I have a lot of local changes I need to integrate regardless, so it's not a big deal to add a quick fix for this. If you prefer to do it / already have it feel free to open one, I'll merge it tonight :)

**Comment by hsahovic** [comment]
This is now merged into master. Are you using the `pip` pickage (in which case I can release a new version with this so you just need to upgrade it) or a local clone (in which case I can wait for other things to get in before a new release)?

**Comment by darrenswhite** [comment]
I'm using the pip package but I've patched it locally anyway :)
