### ISSUE TITLE
Playouts Implementation?

### ISSUE THREAD

**Issue by sudarshanvankudre** [hsahovic/poke-env#130]
Hi, is there any way to "pause" a battle at a certain battle state and try out different actions from that state to the end of the playout? Is this something in the works for the future? Thanks!

**Comment by hsahovic** [comment]
Hey @sudarshanvankudre,

This is on my distant wish list, but not really planned for the next few months.
It would require a deeper integration with showdown. I know that there are utilizes in showdown to serialize battle states, but I don't have a clear view of what is needed to use them as you are describing.

If you take a look at it let me know how it goes!

**Comment by sudarshanvankudre** [comment]
I'll let you know if I figure something out!

**Comment by hsahovic** [comment]
Great :) I'll close this for now then - don't hesitate to reopen or add comments!
