### ISSUE TITLE
Typo in pokemon effect dict

### ISSUE THREAD

**Issue by hamishivi** [hsahovic/poke-env#134]
Hi, great work. Just noticed a small typo at line 275 of `src/poke_env/environment/pokemon.py` - currently the `Effect` type is used in place of what should probably be the `effect` variable:
```diff
def _start_effect(self, effect):
  ...
  elif effect.is_action_countable:
-  self._effects[Effect] += 1
+  self._effects[effect] += 1
```
This can cause runtime errors (albeit rarely with random teams). I've made the fix locally, so happy to make a tiny pr for this if need be :)

**Comment by hsahovic** [comment]
Hi @hamishivi,

Good catch, thanks a lot for bringing this up! I think I'm clearly lacking tests on this set of functionalities. I fixed it on master, I'll push a new release with the fix soon.
Thanks again!
