### ISSUE TITLE
max_concurrent_battles doesn't seem to work properly

### ISSUE THREAD

**Issue by henrycharlesworth** [hsahovic/poke-env#14]
Me again! It seems that the default settings for max_concurrent_battles doesn't work properly - if you run the minimal example from the issue raised yesterday then the players are created with max_concurrent_battles=1, however provided the number of challenges in the cross evaluation is more than one then in fact the players will actually have two battles going on concurrently. This is quite annoying for my current approach which requires only one game between any two players going on at once!

**Comment by hsahovic** [comment]
Hi! Thanks for the report, I'm looking into it. At first glance, it looks like an off-by-one situation in synchronisation primitives. I'll try to find and correct the exact issue ASAP.

**Comment by hsahovic** [comment]
#15 should solve the problem. I will investigate a bit more before merging though, as I'd like to add some tests to prevent this issue from reappearing.

**Comment by hsahovic** [comment]
This issue should be resolved with 0.0.5 :)
