### ISSUE TITLE
model question

### ISSUE THREAD

**Issue by mancho2000** [hsahovic/poke-env#142]
Hi Haris,

How can I  return two different input vectors, process them separately and then concatenate them in a single dense layer?

For example, I would like to return a vector containing the pokedex number of each mon and another vector containing the rest of the battle observations. Then, the pokedex number vector process it with an embedding layer and the other vector with a dense layer. After this, concat both of them into a dense layer which would then be conected to the output layer. Hope it is clear :)

Thank you

**Comment by hsahovic** [comment]
Hey @mancho2000,

Thanks for opening this issue. I'll take a look at it later today :)

**Comment by hsahovic** [comment]
I think there are multiple components to your question.

The first one is returning multiple outputs when embedding a battle. If I build upon the example from the docs, you can do something like:

```python
from poke_env.data import POKEDEX

...

    def embed_battle(self, battle):
        moves_base_power = -np.ones(4)
        moves_dmg_multiplier = np.ones(4)
        for i, move in enumerate(battle.available_moves):
            moves_base_power[i] = (
                move.base_power / 100
            )
            if move.type:
                moves_dmg_multiplier[i] = move.type.damage_multiplier(
                    battle.opponent_active_pokemon.type_1,
                    battle.opponent_active_pokemon.type_2,
                )

        remaining_mon_team = (
            len([mon for mon in battle.team.values() if mon.fainted]) / 6
        )
        remaining_mon_opponent = (
            len([mon for mon in battle.opponent_team.values() if mon.fainted]) / 6
        )


        active_mon_num = POKEDEX[battle.active_pokemon.species]["num"]

        return np.concatenate(
            [
                moves_base_power,
                moves_dmg_multiplier,
                [remaining_mon_team, remaining_mon_opponent],
            ]
        ), active_mon_num
```

Here, we return 1) a vector representing the battle state 2) an int corresponding to the pokedex index of the active pokemon. You can expand this to the opponent's active mon, as well as both teams.

The second part of the question relates to combining this vector with an embedding.

You can do something like:

```python
done = False
battle_state, active_mon_num = env.reset()

while not done:
    embedded_active_mon = mon_embedding[active_mon_num]

    completed_battle_state = np.concat([battle_state, embedded_active_mon])

    action = policy(completed_battle_state)
    (battle_state, active_mon_num), reward, done, _ = env.step(action)
```

However, your question mentions an embedding `layer`, so I imagine this is referring to a keras model. You could build a model with multiple inputs - one for the dense vector state, one for ints to embed - but I don't think this will work with `keras-rl`.
My understanding, which could be wrong as I have not tried it, is that keras-rl requires a simpler, `Sequential` model. If that's the case, you will need to write the training loop yourself, use another framework, or get into the lower level weeds of keras-rl.

Let me know if that helps, and if you get things running as you wanted!

**Comment by mancho2000** [comment]
Thanks for the quick reply!

I found this: https://github.com/keras-rl/keras-rl/issues/287 but I am a beginner and can't manage to make it work. I tried looking into the Keras functional API as well: https://keras.io/guides/functional_api/ with no success. I believe this is what I need, but I don't know how to apply it. Could you please help me out with this? 

I also found how to make a custom model with RLlib in their documentation, i'll give that a shot if I can't make it with keras-rl

**Comment by mancho2000** [comment]
Managed to make it work :)

It makes the learning process much slower though, not sure if it will be practical to use this embedding layer for the pokedex number

**Comment by hsahovic** [comment]
Congrats! How did you set it up?
