### ISSUE TITLE
Installation Error with poke-env

### ISSUE THREAD

**Issue by fwqefwqef2** [hsahovic/poke-env#143]
Hi! I am a long time user of poke-env, and I use poke-env to simulate thousands of games to find optimal team strategies in Metronome Battles. While I was trying to install poke-env on my new laptop, I ran into this issue:

[error.txt](https://github.com/hsahovic/poke-env/files/6349836/error.txt)

I have already tried installing zLib and libjpeg (which are the requirements for Pillow), but I get the same error output. Do you guys know how to solve this?

**Comment by hsahovic** [comment]
Hey @fwqefwqef2,

Thanks for opening this issue. In the logs above, there's

```
RuntimeWarning: Pillow 7.2.0 does not support Python 3.9 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
```

Does your setup requires python 3.9? If not, you can probably fix this by using python 3.7 or python 3.8.

**Comment by fwqefwqef2** [comment]
[error.txt](https://github.com/hsahovic/poke-env/files/6350480/error.txt)

I uninstalled Python 3.9 and downloaded Python 3.8. The same error occurs.

**Comment by hsahovic** [comment]
In the new logs you sent, it looks like python 3.9 is still being used: can you double check with `python --version`?

If 3.8 is correctly being used, I'd recommend using a virtual environment (on windows, I've used conda in the past) or [wls](https://ubuntu.com/wsl). Additionally, I'd recommend checking [this page, which is references by the Pillow error logs](https://pillow.readthedocs.io/en/latest/installation.html#windows-installation).

**Comment by fwqefwqef2** [comment]
I properly downgraded my python to 3.8 and I successfully installed poke_env. Thanks for the help!
