### ISSUE TITLE
battle.fields

### ISSUE THREAD

**Issue by mancho2000** [hsahovic/poke-env#157]
Hi Haris,

It seems to me like sometimes more than one terrain is returned by battle.fields
Could you please look into it

**Comment by hsahovic** [comment]
Hey @mancho2000,

Thanks for reporting this - I'll push a fix tonight.

**Comment by hsahovic** [comment]
@mancho2000 that was an excellent catch - turns out showdown doesn't send a message for fields ending when it's a terrain being replaced :) Thanks a lot for finding this, I really appreciate it! If should be fixed by #158 and `poke-env==0.4.13`
