### ISSUE TITLE
Something weird with player usernames...

### ISSUE THREAD

**Issue by henrycharlesworth** [hsahovic/poke-env#16]
It appears that some choices of usernames are being converted at some point incorrectly. For certain username choices in PlayerConfiguration the code will not run. I haven't looked into this in detail but a few examples:

```
player_1_configuration = PlayerConfiguration("NN P1", None)
player_2_configuration = PlayerConfiguration("NN P2", None)
```
works fine, but:

```
player_1_configuration = PlayerConfiguration("NN p1", None)
player_2_configuration = PlayerConfiguration("NN P2", None)
```
doesn't (I guess the challenges just never get seen/accepted).

```
player_1_configuration = PlayerConfiguration("NN_P1", None)
player_2_configuration = PlayerConfiguration("NN P2", None)
```

also doesn't work.

**Comment by henrycharlesworth** [comment]
in fact weirdly:

```
player_1_configuration = PlayerConfiguration("P11", None)
player_2_configuration = PlayerConfiguration("P21", None)
```
doesn't work, but
```
player_1_configuration = PlayerConfiguration("P1", None)
player_2_configuration = PlayerConfiguration("P2", None)
```
does :s

**Comment by hsahovic** [comment]
Hi! Thanks for the report. I'll look into it - it might wait a bit though, as it is not critical.

**Comment by hsahovic** [comment]
After some investigation, these strange behaviors seem to be caused by showdown's management of usernames. I will add a warning if an unexpected username is returned during login.

**Comment by hsahovic** [comment]
I added the warning.
