### ISSUE TITLE
Creating a heuristics opponent

### ISSUE THREAD

**Issue by mancho2000** [hsahovic/poke-env#172]
Hey Haris,

I am trying to make a new training opponent and have a few questions:

- How do you make it switch? For example, if the mon is weak to its opponent, then switch to a mon that has good typing for it. 
- How do you make it choose a setup move?
- How do you control when it dynamaxes? I would like it to not dynamax too early in the battle
- How do you make it choose a hazards move?

Thanks :)

**Comment by hsahovic** [comment]
Hey @mancho2000,

In your situation, I'd start by taking a look at the [code defining the existing heuristics player](https://github.com/hsahovic/poke-env/blob/058895e11842c074e5345611bed13cf102cc8ef4/src/poke_env/player/baselines.py#L16) - you can use it as a starting point.

Regarding the specifics:

> How do you make it switch? For example, if the mon is weak to its opponent, then switch to a mon that has good typing for it.

`SimpleHeuristicsPlayer` has a [`_should_switch_out`](https://github.com/hsahovic/poke-env/blob/058895e11842c074e5345611bed13cf102cc8ef4/src/poke_env/player/baselines.py#L68) method, that's used when the agent has to make a choice. If it returns `True`, the agent choses the pokemon with the best estimated matchup (as per [`_estimate_matchup`](https://github.com/hsahovic/poke-env/blob/058895e11842c074e5345611bed13cf102cc8ef4/src/poke_env/player/baselines.py#L30)).

This specific mechanism is implemented [here](https://github.com/hsahovic/poke-env/blob/058895e11842c074e5345611bed13cf102cc8ef4/src/poke_env/player/baselines.py#L181).

> How do you make it choose a setup move?

[Here.](https://github.com/hsahovic/poke-env/blob/058895e11842c074e5345611bed13cf102cc8ef4/src/poke_env/player/baselines.py#L147)

> How do you control when it dynamaxes? I would like it to not dynamax too early in the battle

[Here.](https://github.com/hsahovic/poke-env/blob/058895e11842c074e5345611bed13cf102cc8ef4/src/poke_env/player/baselines.py#L45)

> How do you make it choose a hazards move?

[Here.](https://github.com/hsahovic/poke-env/blob/058895e11842c074e5345611bed13cf102cc8ef4/src/poke_env/player/baselines.py#L128)

Keep it mind this agent has not been designed to be extremely competitive - its goal is to be a simple benchmark for more advanced strategies.

Let me know if you have any other question on that topic :)
