### ISSUE TITLE
Make long constants hidden by default in documentation.

### ISSUE THREAD

**Issue by yoursred** [hsahovic/poke-env#174]
In the documentation, some really long constants are displayed, which makes browsing said documentation very annoying.
Here's an example with the doc page for 'Move':
![Screenshot from 2021-06-29 05-55-41](https://user-images.githubusercontent.com/86563891/123745138-5c028200-d89f-11eb-8643-95c148cc564a.png)
![Screenshot from 2021-06-29 05-55-46](https://user-images.githubusercontent.com/86563891/123745144-5d33af00-d89f-11eb-9a9b-53949aa69e01.png)
![Screenshot from 2021-06-29 05-55-48](https://user-images.githubusercontent.com/86563891/123745146-5e64dc00-d89f-11eb-858a-2f298abf5058.png)
![Screenshot from 2021-06-29 05-55-51](https://user-images.githubusercontent.com/86563891/123745150-602e9f80-d89f-11eb-9a80-20411119cadd.png)
![Screenshot from 2021-06-29 05-55-53](https://user-images.githubusercontent.com/86563891/123745155-615fcc80-d89f-11eb-9167-1efb643bf800.png)
![Screenshot from 2021-06-29 05-55-56](https://user-images.githubusercontent.com/86563891/123745162-6290f980-d89f-11eb-973a-709711f05176.png)
![Screenshot from 2021-06-29 05-55-59](https://user-images.githubusercontent.com/86563891/123745163-645abd00-d89f-11eb-890c-d7a6466ebf25.png)
![Screenshot from 2021-06-29 05-56-02](https://user-images.githubusercontent.com/86563891/123745168-658bea00-d89f-11eb-8095-0ebc651a2c49.png)

As you can see this goes on for quite a while and makes browsing the docs very cumbersome.
I suggest either creating a page or set of pages just for these constants, or putting them in spoilers if possible.

**Comment by hsahovic** [comment]
Hey @yoursred,

Thanks for bringing this up. A [similar fix](https://github.com/hsahovic/poke-env/commit/3059e9fa2b35edca1d174bcbcd2e53ca2aabbf57) was pushed to master, but wasn't accompanied by a dedicated release. `poke-env`'s _latest_ docs are fixed, but not _stable_. I am going to change the default docs to _latest_ over _stable_; this should fix the version that is displayed and reduce the risk of similar issues popping up in the future.

Thanks for your help!
