### ISSUE TITLE
connecting_an_agent_to_showdown.py works fine, very confused on how to implement reinforcement learning

### ISSUE THREAD

**Issue by IndigoGems** [hsahovic/poke-env#177]
I have all the proper packages installed (Python 3.6, Tensorflow 2,  keras-rl2, and all that)

Tried to run rl_with_open_ai_gym_wrapper.py but results in Connect call failed

I am sorry if this is not the right place

My guess is that I would have to use both .py files as a reference and create one file that has an agent that connects to either Showdown or local and uses the training code

**Comment by hsahovic** [comment]
Hi @IndigoGems,

Thanks for reaching out.

For the connect call failed error:

- Did you specify a showdown username and password [in the script](https://github.com/hsahovic/poke-env/blob/058895e11842c074e5345611bed13cf102cc8ef4/examples/connecting_an_agent_to_showdown.py#L12)?
- If so, can you copy-paste the logs and error traceback?

For using RL on PS: I'd recommend training your agents locally (as training a model on PS would take a way too long, at least as far as I can tell) and then using this training agent on PS. To do so, you'd probably train and save the model, and then load it separately in another script.

**Comment by IndigoGems** [comment]
Ah, it seems that I have solved the issue. Thank you.

However I am worried about me launching my own local showdown server with the --no-security flag. The server runs fine but I cannot use SimpleRLPlayers or RandomPlayer because I did not use the flag. So my learning agent won't work. 

Is the flag okay to use locally?

**Comment by hsahovic** [comment]
That's good to hear.

As long as it's for local use, yes, you can use the `--no-security` flag without having to worry about it.

If you are not using it, you will need to specify username / passwords for your agents (as in the [connecting an agent to showdown example](https://github.com/hsahovic/poke-env/blob/058895e11842c074e5345611bed13cf102cc8ef4/examples/connecting_an_agent_to_showdown.py#L12)), and training will be significantly slower.

**Comment by IndigoGems** [comment]
The training locally seems to have worked fine, and the output was a folder named "model_10000".

I really hope this is the last question: How would I load my trained model onto an agent with authentication? (So that the bot can challenge other players in Showdown)

**Comment by hsahovic** [comment]
Well done! You should be able to load your model using `tensorflow.keras.models.load_model` and use it in a custom agent by doing something a bit like [what is mentioned is in this issue](https://github.com/hsahovic/poke-env/issues/119).
You can then use the same code as in the connecting to PS example, replacing the random player with this one.

**Comment by IndigoGems** [comment]
Thank you once again. I'll try to make this all work with my own hands from now on.
