### ISSUE TITLE
Pokemon pokedex entry

### ISSUE THREAD

**Issue by cjyu81** [hsahovic/poke-env#181]
After looking through the pokemon.py file, I noticed there is a species identifier but no pokedex entry number for each pokemon object. My goal is to number each pokemon species off for input to a network. Is there a built in method of accessing the pokemon's pokedex number or another effective approach to assigning each species a number?

**Comment by hsahovic** [comment]
Hey @cjyu81,

There is no built in method to do so, but you can build and use a `dict` object to do so:

Before instantiation:

```python
from poke_env.data import POKEDEX  # if you are not playing in gen 8, you might want to do import GENX_POKEDEX instead

SPECIES_TO_DEX_NUMBER = {}

for species, values in POKEDEX.items():
    SPECIES_TO_DEX_NUMBER[species] = values['num']
```

In your code:
```python
def choose_move(self, battle):
    active_mon_dex = SPECIES_TO_DEX_NUMBER[battle.active_pokemon]
```

That being said, you might want to expand this approach to separate different regional forms, megas, and what not:

```python
from poke_env.data import POKEDEX
from poke_env.utils import to_id_str

SPECIES_TO_CUSTOM_ID = {}

idx = 0
for species, values in POKEDEX.items():
    SPECIES_TO_DEX_NUMBER[species] = idx
    idx += 1
    for other_form in values['otherFormes']:
        SPECIES_TO_DEX_NUMBER[to_id_str(other_form)] = idx
        idx += 1
```

Would that kind of approach work on your end?

**Note:** I haven't tested the code above

**Comment by cjyu81** [comment]
After testing the code above, I found it worked great for my purposes. I made two small edits to make it runnable:

`active_mon_dex = self.SPECIES_TO_DEX_NUMBER[battle.active_pokemon.species]`
'battle.active_pokemon' -> 'battle.active_pokemon.species'

`    idx = 0
    for species, values in POKEDEX.items():
        SPECIES_TO_DEX_NUMBER[species] = idx
        idx += 1
        if 'otherFormes' in  values:
            for other_form in values['otherFormes']:
                SPECIES_TO_DEX_NUMBER[to_id_str(other_form)] = idx
                idx += 1`
'if 'otherFormes' in  values:' added

Closing the ticket as my question is answered
