### ISSUE TITLE
Weird RL Envirmonment Error

### ISSUE THREAD

**Issue by haasj22** [hsahovic/poke-env#182]
Hey. I was trying to use your project for a program I was working on and I used the reinforcement learning tutorial. At one point I had it working but recently I get the following error.

2021-07-19 00:53:53,492 - RandomPlayer 1 - CRITICAL - Error message received: |nametaken|RandomPlayer 1|Your authentication token was invalid.
2021-07-19 00:53:53,493 - RandomPlayer 1 - ERROR - Unhandled exception raised while handling message:
|nametaken|RandomPlayer 1|Your authentication token was invalid.

For some reason getting it to authenticate users always fails. As I've gotten this working in the past, I know I have the right versions of python and keras installed. Any other suggestions as to what could cause this issue. I'm currently just testing it on the base example code on the repo. Thanks.

**Comment by hsahovic** [comment]
Hi @haasj22,

Are you running pokemon showdown locally? If so, did you start it with the `--no-security` flag?
