### ISSUE TITLE
Rough ELO of bots

### ISSUE THREAD

**Issue by ID56** [hsahovic/poke-env#185]
Hello! I just wanted to get an idea of the current state of RL agents for showdown. Are there any records of ELO scores for the bots on any metas (e.g. random battle)?

**Comment by hsahovic** [comment]
Hey @ID56!

I know that there are a couple of RL projects out there, but I'm not sure what kind of results they are getting. [Here is one particular project with a good write up](https://www.yuzeh.com/assets/CoG-2019-Pkmn.pdf). Relevant extract:

> At the end of 500 training iterations, RL-rb attains a 1677 Glicko-1 rating, which roughly corresponds to a 72% chance of defeating an opponent selected uniformly at random from the ladder.

**Comment by ID56** [comment]
@hsahovic Thanks! This is exactly what I was looking for.
