### ISSUE TITLE
Does not track multiple layers of side conditions

### ISSUE THREAD

**Issue by pmariglia** [hsahovic/poke-env#187]
Side conditions that can have multiple layers (spikes/toxicspikes) do not have their layer count tracked. When tracking side conditions this environment uses a key-value map where the key is the name of the side condition and the value is the turn that the side condition was set on.

[This is done here](https://github.com/hsahovic/poke-env/blob/606a288ade88a1e664ab946c9510f1acc13b003d/src/poke_env/environment/abstract_battle.py#L544).

**Comment by hsahovic** [comment]
Good catch - that's definitely an error. I'll get a fix out asap.
