### ISSUE TITLE
Locked moves

### ISSUE THREAD

**Issue by mancho2000** [hsahovic/poke-env#189]
Hi Haris!

Does the agent understand it is locked into a move because of a choice item / locking move like outrage? How can I add this to my model?

Also similar to this, does it understand that it cant switch because of moves like whirpool?

**Comment by hsahovic** [comment]
Hey @mancho2000,

Thanks for bringing this up.
I'm not 100% sure of the actual behavior in all of these case, but my understanding is that:

- You can detect if your pokemon has a choice item by checking [`mon.item`](https://poke-env.readthedocs.io/en/latest/pokemon.html?highlight=Pokemon#poke_env.environment.pokemon.Pokemon.item)
- If your pokemon is currently locked into a move, it will be the only move listed in `battle.available_moves`
- If your pokemon is confirmed trapped (eg. whirpool), [`battle.trapped`](https://poke-env.readthedocs.io/en/latest/battle.html?highlight=trapped#poke_env.environment.battle.Battle.trapped) will be set to `True`. If your pokemon may be trapped (eg. unrevealed shadow tag), trying to switch will fail and re-trigger a move decision for which [`battle.trapped`](https://poke-env.readthedocs.io/en/latest/battle.html?highlight=trapped#poke_env.environment.battle.Battle.trapped) will be `True`
I hope this helps - let me know if anything else is unclear!
