### ISSUE TITLE
Unknown item vs No item

### ISSUE THREAD

**Issue by bubloo7** [hsahovic/poke-env#193]
battle.opponent_active_pokemon.item has the value None when the item the enemy pokemon has is unknown or if it has no item (for example if I used knock off or have the ability frisk and see that it has no item).  Is there a way to make it differentiate between the two scenarios? Maybe if the item the pokemon is holding is unknown it just holds the value "unknown" and if it has no item it has the value None. It's not that big of a deal but I was just wondering!

**Comment by hsahovic** [comment]
Hey @bubloo7,

Thanks for opening this issue. Unless there is a bug in the current implementation, `poke_env.Pokemon.item` should be equal to `poke_env.data.UNKNOWN_ITEM` if its item is unrevealed.

**Comment by bubloo7** [comment]
I think there is a bug then, unfortunately. The item always has the value None when it's unrevealed for me. I used this code [here](https://github.com/bubloo7/PokeBot/blob/main/ScanBot.py). Line 46 always prints "Enemy Item:  None".

**Comment by hsahovic** [comment]
@bubloo7 which version of `poke-env` are you using? Using `0.4.18` I get:

```
___________Turn #1___________
~~~~~MOVES~~~~~
Available Switches:  [toxicroak (pokemon object) [Active: False, Status: None], reshiram (pokemon object) [Active: False, Status: None], hitmonchan (pokemon object) [Active: False, Status: None], blastoise (pokemon object) [Active: False, Status: None], polteageist (pokemon object) [Active: False, Status: None]]
Available Moves:  [quickattack (Move object), flareblitz (Move object), facade (Move object), superpower (Move object)]
~~~~~Active Pokemon~~~~~
Opp Pokemon:  registeel (pokemon object) [Active: True, Status: None]
My Pokemon:  flareon (pokemon object) [Active: True, Status: None]
~~~~~My STATS~~~~~
My level:  86
My Stats:  {'atk': 273, 'def': 152, 'spa': 213, 'spd': 238, 'spe': 161}
My Item:  toxicorb
My Ability:  guts
~~~~~Enemy STATS~~~~~
Enemy level:  83
Enemy Stats:  {'atk': None, 'def': None, 'spa': None, 'spd': None, 'spe': None}
Enemy Item:  unknown_item
Enemy Ability:  None
~~~~~BOOSTS~~~~~
My Boosts:  {'accuracy': 0, 'atk': 0, 'def': 0, 'evasion': 0, 'spa': 0, 'spd': 0, 'spe': 0}
Enemy Boosts:  {'accuracy': 0, 'atk': 0, 'def': 0, 'evasion': 0, 'spa': 0, 'spd': 0, 'spe': 0}
~~~~~FIELD~~~~~
Fields:  {}
Weather:  {}
My Side Conditions:  {}
Opp Side Conditions:  {}
```

**Comment by bubloo7** [comment]
I thought I made sure I was using the latest version before I made this post but I was looking at the wrong venv 😐  Sorry for the confusion it works perfectly after I made sure I'm using the newest version!
