### ISSUE TITLE
file missing repl

### ISSUE THREAD

**Issue by godpow** [hsahovic/poke-env#194]
C:\Users\CyberKira\Documents\pokemon showdown\pokemon-showdown>node pokemon-showdown start --no-security
RESTORE CHATROOM: lobby
RESTORE CHATROOM: staff

CRASH: Error: ENOENT: no such file or directory, scandir 'C:\Users\CyberKira\Documents\pokemon showdown\pokemon-showdown\logs\repl'
    at Object.readdirSync (fs.js:1043:3)
    at _class.start (C:\Users\CyberKira\Documents\pokemon showdown\pokemon-showdown\lib\repl.ts:12:16)
    at Object.<anonymous> (C:\Users\CyberKira\Documents\pokemon showdown\pokemon-showdown\server\index.ts:173:11)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.m._compile (C:\Users\CyberKira\Documents\pokemon showdown\pokemon-showdown\node_modules\ts-node\src\index.ts:1310:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\CyberKira\Documents\pokemon showdown\pokemon-showdown\node_modules\ts-node\src\index.ts:1313:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Object.<anonymous> (C:\Users\CyberKira\Documents\pokemon showdown\pokemon-showdown\pokemon-showdown:134:22)

SUBCRASH: Error: ENOENT: no such file or directory, open 'C:\Users\CyberKira\Documents\pokemon showdown\pokemon-showdown\logs\errors.txt'

Worker 1 now listening on 0.0.0.0:8000
Test your server at http://localhost:8000
![image](https://user-images.githubusercontent.com/17231911/132939678-8d054739-aa26-42fd-b16a-ae3f35272f09.png)

**Comment by godpow** [comment]
Am I missing a step or something?

**Comment by hsahovic** [comment]
Hey @godpow,

Thanks for reaching out. This seems to be a pokemon-showdown issue - if you do not find a fix, I would recommend reaching out to them.
I am not sure what is causing this error, but other people with similar error messages [like here](https://github.com/sass/node-sass/issues/1579) or [here](https://stackoverflow.com/questions/45251645/error-enoent-no-such-file-or-directory-scandir) got results by rebuilding the faulty library. Maybe something like `npm build` or `npd rebuild .` could help?

**Comment by hsahovic** [comment]
One other thing that may be helpful: it looks like you are using windows. I would recommend taking a look at [WLS](https://ubuntu.com/wsl), as it gives you access to a linux terminal directly from your windows environment, which makes working with libraries like pokemon-showdown a lot easier.

**Comment by godpow** [comment]
I installed ubuntu on a spare hard drive seems like the same issue 
[linux.txt](https://github.com/hsahovic/poke-env/files/7151092/linux.txt)
![Screenshot from 2021-09-12 22-59-13](https://user-images.githubusercontent.com/17231911/133017883-785daf1e-b690-4008-90f3-e64def86f33d.png)

**Comment by godpow** [comment]
I can get on showdown just fine in a browser.

**Comment by hsahovic** [comment]
Which version of `node` are you using?

**Comment by godpow** [comment]
On windows and linux node 14

**Comment by hsahovic** [comment]
Can you try upgrading to node 15?

**Comment by godpow** [comment]
I didn't see node 15 for windows so I upgraded to 16 still same issue on windows. I'll try it on linux in a while

**Comment by hsahovic** [comment]
@godpow I tried running my ci scripts and encountered the same issue - I think there is something broken in PS's current main branch, or they recently changed something that broke the installation steps I'm using.
I'll open an issue in their repo. Feel free to chime in :)

**Comment by godpow** [comment]
Ok hopefully it'll be fixed soon!

**Comment by godpow** [comment]
C:\Users\CyberKira\Documents\pokemon showdown\pokemon-showdown>node pokemon-showdown start --no-security
RESTORE CHATROOM: lobby
RESTORE CHATROOM: staff
Worker 1 now listening on 0.0.0.0:8000
Test your server at http://localhost:8000 


it seems like making all of the directories fixed the issue. I have another question though how do you connect the bot to showdown and not a local server?

**Comment by godpow** [comment]
![Uploading image.png…]()

**Comment by hsahovic** [comment]
Good job! Thanks again for bringing up this issue, it was a good catch.
Regarding connecting to showdown, [I think you should find what you need here](https://poke-env.readthedocs.io/en/latest/connecting_to_showdown_and_challenging_humans.html). Let me know if something isn't clear!

**Comment by godpow** [comment]
> Good job! Thanks again for bringing up this issue, it was a good catch.
> Regarding connecting to showdown, [I think you should find what you need here](https://poke-env.readthedocs.io/en/latest/connecting_to_showdown_and_challenging_humans.html). Let me know if something isn't clear!
I have both pokemon-showdown and poke-env but I'm a bit confused on where to go from here. I looked in the server configuration and replaced the localhost:8080 with https://play.pokemonshowdown.com/action.php?. Not sure what to do to be honest.

**Comment by hsahovic** [comment]
When instantiating a `Player` object, pass `server_configuration=ShowdownServerConfiguration` and `player_configuration=PlayerConfiguration("showdown_username", "showdown_password")` - this will make it connect to showdown's server with the given username / password.
