### ISSUE TITLE
Calling reset twice in a row on PlayerEnv hangs.

### ISSUE THREAD

**Issue by Benjamin-Etheredge** [hsahovic/poke-env#199]
While testing out custom player environments with the `dqn_training` wrapper, I noticed calling `player_env.reset()` twice in a row was causing the code to hang.

This could be due to my specific environment, but it might be worth investigating as third-party software does strange things like call reset twice in a row (e.g. see `Agent.__init__` at https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/domain_templates/reinforce_learn_Qnet.py)

**Comment by hsahovic** [comment]
Hey @Benjamin-Etheredge,

Thanks for opening this issue. This is a known issue that has been sitting in my backlog for quite some time now; it might be time to implement a fix. I'll take a deeper look at it over the weekend.

**Comment by hsahovic** [comment]
This should be fixed by 7a8e967d8728596a1804655ae78f3030b5407533.

**Comment by hsahovic** [comment]
This is fixed in release `0.4.19`.
