### ISSUE TITLE
Hidden Power Typing

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#202]
Hey Haris,

Was just writing some unit tests to make sure I am properly embedding moves and I noticed some weird behavior with Hidden Power:

<img width="238" alt="Screen Shot 2021-09-17 at 1 20 30 PM" src="https://user-images.githubusercontent.com/8413475/133848960-0fc35c66-788a-4a9d-b97b-6aa1a35cee55.png">

I would imagine that Hidden Power Bug's typing should be Bug, especially given that the typing in the JSON file is Bug

**Comment by hsahovic** [comment]
Hey @caymansimpson,

Good catch. I'll try to get a fix asap.

**Comment by hsahovic** [comment]
This should be fixed by 86ab5a678ad6f62e8738c616327c4d881a046535. It will be part of the next release.

**Comment by hsahovic** [comment]
This is fixed in release `0.4.19`.
