### ISSUE TITLE
5 moves appearing in pokemon.moves

### ISSUE THREAD

**Issue by Benjamin-Etheredge** [hsahovic/poke-env#209]
Periodically, 5 moves appear in the `pokemon.moves` field. ~50% of the time seems due to copycat, But I'm still seeing it with other moves. This issue is to track why.

```
'calmmind': calmmind (Move object),
'darkpulse': darkpulse (Move object),
'fireblast': fireblast (Move object),
'psyshock': psyshock (Move object),
'shadowball': shadowball (Move object)
---------------------------------------------
copycat one
---------------------------------------------
'copycat': copycat (Move object),
'headsmash': headsmash (Move object),
'knockoff': knockoff (Move object),
'playrough': playrough (Move object),
'thunderwave': thunderwave (Move object)
```

**Comment by hsahovic** [comment]
Thanks for bringing this up. I am working on a fix, but it is currently breaking other part of the parsing logic - I'll fix it properly sometime this week.

**Comment by Benjamin-Etheredge** [comment]
No worries. I figured you could get to the bottom of it way faster than I could. I'm just ignoring the 5th move for now.

**Comment by hsahovic** [comment]
#215 should take care of it :)

**Comment by Benjamin-Etheredge** [comment]
I had no idea it would be that involved. Awesome work!
