### ISSUE TITLE
Bug: AbstractBattle._weather is mixing dicts with Weather type

### ISSUE THREAD

**Issue by Benjamin-Etheredge** [hsahovic/poke-env#212]
I noticed `AbstractBattle.weather` was returning dicts sometimes when the type hint said `Weather`. I noticed some parts of the code base store it as a dict of what turns it activated. Was this intentional or a missed change?

**Comment by hsahovic** [comment]
This is a good catch. I think the implementation was meant to be a one-size dict mapping the active weather to its activation turn. That being said, I can see why it would make sense for it to be a simple `Weather` object instead. If we were to implement that change, how do you think we should store the weather activation turn? A separate attribute?

**Comment by Benjamin-Etheredge** [comment]
That's a good question. I'm not sure we should care about the weather activation turn right now. I feel like keeping up with the history of how long ago it was up fits nicely into a future history tracking feature.

For now, I'm tracking weather in my agent by just stacking battle embeddings for history. The networks can see a weather embedding and figure out it changed and how long it might go on.

**Comment by hsahovic** [comment]
Fixed by 30462cecd2e947ab6f0b06b0f2febbdde3918366 - `battle.weather` is now always (and documented as) a `dict` mapping up to one `Weather` object to an `int` corresponding to its start turn.
