### ISSUE TITLE
Inconsistency in AbstractBattle vs Battle

### ISSUE THREAD

**Issue by akashsara** [hsahovic/poke-env#221]
Hi,
There seem to be a few inconsistencies within the Battle objects. I don't think they really affect anything in terms of implementation, but it required me to jump around between different pieces of the documentation and the code to figure things out.

1. AbstractBattle has a method `opponent_can_dynamax` but no `can_dynamax`. While both are implemented in Battle, it's just a bit strange that `can_dynamax` doesn't exist, even as an abstract method.
2. AbstractBattle has methods `can_mega_evolve` and `can_z_move` but no corresponding version for the opponent.  There is no implementation of the same in the Battle object either. 

Also on a different note, I was wondering how the opponent aspect works. I'm essentially trying to build a larger state that encompasses all the battle knowledge into it. If I were to do something like `battle.opponent_active_pokemon.moves`, would I receive only the moves it has used so far in the battle? If yes, what format would this be in? Would I only get a dict of the moves known or would I get a dict of exactly 4 items but the unknown ones are blank?

**Comment by hsahovic** [comment]
This should be fixed by #232
