### ISSUE TITLE
Difference in ability name format between Pokemon.possible_abilities and Pokemon.abilities

### ISSUE THREAD

**Issue by akashsara** [hsahovic/poke-env#223]
Title essentially.

I got:
```
>> pokemon.possible_abilities
{'0': 'Poison Point', '1': 'Rivalry', 'H': 'Sheer Force'}
>> pokemon.ability
sheerforce
```
Is there any reason for this difference in text formats? Reasons aside, I was wondering if this was just a matter of lower casing and removing spaces? If that's all is happening, I can handle the difference in code.

The Pokemon in question is Nidoking if that's necessary. 

Also, according to the documentation `Pokemon.possible_abilities` is supposed to have a format of `List[str]`.  whereas here it seems to be a dict.

**Comment by akashsara** [comment]
okay so after some digging, I've found two places that set a Pokemon's ability:

```
def _update_from_pokedex(self, species: str, store_species: bool = True) -> None:
        ...
        self._possible_abilities = dex_entry["abilities"]

        if len(self._possible_abilities) == 1:
            self._ability = self._possible_abilities["0"]  # pyre-ignore
        ...
```
Here the ability is coming from the Pokedex.json file. Everything is set to the `Sheer Force` format here.

and

```
def _update_from_request(self, request_pokemon: Dict[str, Any]) -> None:
        ...
        if "ability" in request_pokemon:
            self._ability = request_pokemon["ability"]
        elif "baseAbility" in request_pokemon:
            self._ability = request_pokemon["baseAbility"]
        ...
```
I'm not sure where the ability name is coming from here, but it seems like it's of the `sheerforce` format.

Having separate formats is something that I can tackle via code but there is one special case here that might pose problems. The conditional statement in the `_update_from_pokedex` function above doesn't seem to apply this formatting there.

**Comment by hsahovic** [comment]
This should be fixed by #227

**Comment by hsahovic** [comment]
#227 is merged, and will be released later today with version `0.4.21`.

Thanks a lot for your feedback @akashsara - I really appreciate. Let me know if you find any other issues!

**Comment by akashsara** [comment]
Awesome, thank you for all the help! Am I right in assuming `sheerforce` will be the format used everywhere then?

**Comment by hsahovic** [comment]
Yes, that is correct.
