### ISSUE TITLE
Question: usefulness of _register_teampreview_pokemon

### ISSUE THREAD

**Issue by Angelo942** [hsahovic/poke-env#233]
Hi, I was editing the AbstractBattle class to help me work on predicting information about the enemy team and in particular I wanted to change _register_teampreview_pokemon¹ to fill from the start _opponent_team when we know the composition. 
Reading the comments² I thought the reason why wasn't implemented this way is that during doubles the identifier depends on which side the pokemon first appears on and so we can't know it from the beginning, but I wanted to bypass it by simply ignoring the 3rd character and realized that get_pokemon is already doing it³. Then why do we still have _register_teampreview_pokemon and why does opponent_team only returns the pokemon that have been sent on the field ?

here are the parts of the code I'm referring to

```py    
1)
def _register_teampreview_pokemon(self, player: str, details: str):
        if player != self._player_role:
            mon = self.POKEMON_CLASS(details=details)
            self._teampreview_opponent_team.add(mon)
```

```py
2)
@property
    def opponent_team(self) -> Dict[str, Pokemon]:
        """
        During teampreview, keys are not definitive: please rely on values.

        :return: The opponent's team. Keys are identifiers, values are pokemon objects.
        :rtype: Dict[str, Pokemon]
        """
        if self._opponent_team:
            return self._opponent_team
        else:
            return {mon.species: mon for mon in self._teampreview_opponent_team}
```

```py
3)
    def get_pokemon(
        self,
        identifier: str,
        force_self_team: bool = False,
        details: str = "",
        request: Optional[dict] = None,
    ) -> Pokemon:
        """ 
        [...]
        """
        if identifier[3] != " ":
            identifier = identifier[:2] + identifier[3:]
        [...]
```

And this is a test I made to see if it could already work just like this and it seems to do so.
```py
    def _register_teampreview_pokemon(self, player: str, details: str):
        if player != self._player_role:
            name = details.split(",")[0]
            self.get_pokemon(identifier=f"{player}: {name}")
```

**Comment by hsahovic** [comment]
Hey @Angelo942,

This is a good question. The short answer is that not all pokemons shown in teampreview will take part in the battle (think VGC, where you pick 4 out of 6 mons).
The longest answer is that this code was part of the doubles support feature, and was kind of overlooked - we could deal with teampreview more thoughtfully.

Here are three improvements I'll implement that come to mind:

- If all mons are brought, then we can build `_opponent_team`
- `_teampreview_opponent_team` should be accessible from a public property
- `_teampreview_opponent_team` and `_teampreview_opponent_team` should point to the same underlying objects

Are there other things that you think would make sense on that subject?

**Comment by Angelo942** [comment]
> not all pokemons shown in teampreview will take part in the battle  

Oh, I missed that part.
I don't have a particular need for the teampreview so I don't know what could be improved, but just including it in the documentation may already be interesting.

What do you mean by with the third point?
 
(And for problems with different forms yes, I ended up - please don't cry seeing how I'm brutalizing your code (/▿＼ ) - just changing it to `f"{player}: {name.split('-')[0]}"` to split out the species which does the job for what I need right now)
