### ISSUE TITLE
Typo in abstract_battle: get_pokemon

### ISSUE THREAD

**Issue by Angelo942** [hsahovic/poke-env#235]
Hi, the error for exceeding the team limit¹ had the intention to show which Pokemon we are trying to add, right? 
```py
        if self._team_size and len(team) >= self._team_size[player_role]:
            raise ValueError(
                "%s's team already has %d pokemons: cannot add %s to %s"
                % (
                    player_role,
                    self._team_size[player_role],
                    identifier[:2],
                    ", ".join(team.keys()),
                )
            )
```  
for now the code just repeats the player_role (identifier[:2]) instead of writing the Pokemon's name or the full identifier:
> ValueError: p1's team already has 6 pokemons: cannot add **p1** to p1: Kyurem, p1: Tapu Koko, p1: Corviknight, p1: Landorus-Therian, p1: Heatran, p1: Tapu Fini

**Comment by hsahovic** [comment]
Thanks for the report @Angelo942 - that's a good catch.
