### ISSUE TITLE
Bug with Pokemon.preparing

### ISSUE THREAD

**Issue by akashsara** [hsahovic/poke-env#239]
Hi Haris,
There's a bug with the `Pokemon._prepare`. Specifically, it's supposed to return a boolean value and when there is no preparation it does return False. However, when it's supposed to return True it instead returns a tuple of `(move, target)` (Ref: pokemon.py line 261). So instead of receiving True, I receive something like `('Bounce', None)`.

I would change it myself and submit a PR but I'm not sure if this format is necessary for something else.

**Comment by hsahovic** [comment]
Hey @akashsara,

Thanks for opening this issue. I'll look into it.

**Comment by hsahovic** [comment]
Good catch - it should be fixed! You can now do `pokemon.preparing_move` and `pokemon.preparing_target`, in addition to `pokemon.preparing`.
