### ISSUE TITLE
How can I see the log of a battle?

### ISSUE THREAD

**Issue by edugzlez** [hsahovic/poke-env#249]
I'm trying to get the statuses and actions performed in a battle. 

It's possible? How can I do it?

**Comment by hsahovic** [comment]
Hey @edugzlez,

If depends what you want to do exactly. If it's only for review / understanding what's going on, you can:
- Display logs of battles by setting `log_level=20` when instanciating a `Player` object. This will log every message received and sent to showdown, encoded with `<<<` or `>>>` starting characters
- Save battle replays by setting `save_replays=True` when instanciating a `Player` object. This will create html replay files after each battle.

If you want to access that data programmatically, there's no built-in mechanism for that exact purpose, but depending on what you want / need it could be fairly easy to add. Let me know if you want to discuss :)

**Comment by edugzlez** [comment]
That's enough. Thanks!
