### ISSUE TITLE
NotImplementedError during training

### ISSUE THREAD

**Issue by jbferdinand** [hsahovic/poke-env#27]
Hello,
When using the rl_with_open_ai_gym_wrapper script, my training (using gen7randombattle) often stops because of a "NotImplementedError". Here are the actions it fails to parse:

`NotImplementedError: ['', '-block', 'p2a: Ribombee', 'ability: Sweet Veil', '[of] p2a: Ribombee']`
or
`NotImplementedError: ['', '-block', 'p2a: Aromatisse', 'ability: Aroma Veil', '[of] p2a: Aromatisse']`

It looks like "-block" is what's causing the issue.

**Comment by hsahovic** [comment]
Hi Jean-Baptiste,

Thanks for reporting this issue. I'll investigate and let you know asap :)

**Comment by hsahovic** [comment]
Hi Jean-Baptiste,

I identified the problem: `-block` is a type of message that was introduced recently by Pokemon Showdown. When I updated our recommended fork of Showdown two days ago, I introduced this type of message in it. I also updated the Master branch of `poke-env` to manage these messages properly (see recent commits for more details), but I did not push a new version of the project on Pypi.

The reason for that is that I wanted to conduct additional tests regarding performance before publishing a new version of the project; I did not realize that someone downloading this combination of versions could have problems running it. My apologies for that!

I'll push a new version of Pypi asap, incorporating these changes :)

**Comment by hsahovic** [comment]
Done! Version `0.1.2` should solve your problem; you just need to `pip install --upgrade poke-env`.

**Comment by jbferdinand** [comment]
Thanks for the quick fix and most of all for creating this amazing project, Haris ! :-)
