### ISSUE TITLE
reset_env() fails if no battles have been played yet

### ISSUE THREAD

**Issue by akashsara** [hsahovic/poke-env#312]
Hi, I'm using the latest version (as of two days ago) of the code here.

I call `player.reset_env()` multiple times to evaluate my model against different opponents. However, if the player hasn't played any battles before this call, it fails giving the following error:

`'NoneType' object has no attribute 'finished'`

I dived into the code and the problem seems to be in L520 of `openai_api.py`:

```
async def _stop_challenge_loop(
        # removed code above
        if force:
            if not self.current_battle.finished:  # pyre-ignore <---- this line
                if not self.actions.empty():
        # removed code below
```

The fix is simple `if self.current_battle is not None and not self.current_battle.finished` and I'm happy to put up a PR, but just wanted to check if this is indeed a bug and not intentional.

**Comment by hsahovic** [comment]
I think this is a bug. I'd be happy to merge a PR for it :)

**Comment by MatteoH2O1999** [comment]
Yep,
didn't notice that.
Thanks @akashsara !!!

**Comment by hsahovic** [comment]
Thanks @akashsara ! I merged your fix in :)
