### ISSUE TITLE
Max Damage Player Example Not Running

### ISSUE THREAD

**Issue by dhuey2** [hsahovic/poke-env#325]
Hello, I downloaded poke-env from github and have been trying to run one of the example files but keep encountering this error. Im wondering if its a problem with my installation or if I'm missing something. Thanks

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/98057485/186724010-b0c973ab-ed76-4d46-8a94-55916c9897e6.png">

**Comment by akashsara** [comment]
From #305, it seems like you need a specific version of gym. Try `pip install gym==0.24.1`
