### ISSUE TITLE
Gen 9 support

### ISSUE THREAD

**Issue by hsahovic** [hsahovic/poke-env#341]
Title.

**Comment by hsahovic** [comment]
Singles support for tera in #351, as well as effects used in random battles.
All effects, doubles, baseline agents and updated exampled will follow in separate PRs.
This are good first issues, in case anyone is interested :)

**Comment by bkc39** [comment]
what is the current status of this? I'd be interested in contributing to some of the follow up issues

**Comment by kodecreer** [comment]
I implemented this in a current build of mine.
