### ISSUE TITLE
Replace `gym` with `gymnasium`

### ISSUE THREAD

**Issue by DiTo97** [hsahovic/poke-env#353]
Hi @hsahovic,

As of last week, the maintainance of OpenAI's Gym Iibrary as fully moved to [Gymnasium](https://gymnasium.farama.org/).

I think it would be wise to update all the code related to reinforcement learning to point to the new library instead. It should just be a matter of replacing this line of code:

```python
import gym
```

with this line of code:

```python
import gymnasium as gym
```

The compatibility with the old Gym library should be there for the most part, besides a few things well-documented [here](https://gymnasium.farama.org/content/gym_compatibility/).

**Comment by acxz** [comment]
@hsahovic would you review a PR if I made on closing this issue?
I also believe that it is important to move to gymnasium.

**Comment by hsahovic** [comment]
@acxz could you link the PR here?

**Comment by patilanuja** [comment]
@hsahovic Can I work on this issue?

**Comment by patilanuja** [comment]
Will you please assign this task to me?

**Comment by hsahovic** [comment]
@patilanuja did you have a chance to take a look at this?

**Comment by acxz** [comment]
If @patilanuja doesn't end up responding, I'll submit a PR by the end of this week. I started the work for this, but I remember something came up and I wasn't able to finish it.

**Comment by hsahovic** [comment]
@cameronangliss fixed it with https://github.com/hsahovic/poke-env/pull/467

**Comment by acxz** [comment]
Great! Thanks @cameronangliss !
