### ISSUE TITLE
Trying to access stats of an opposing pokemon that Zoroark was disguised as earlier gives AtrributeError

### ISSUE THREAD

**Issue by Akkete** [hsahovic/poke-env#357]
Trying to access `mon.stats` and `mon.pokeball` gives an AttributeError, when `mon` is opponent active pokemon that Zoaroark has illusioned as earlier in the battle.

For example trying to access `mon.pokeball` gives the following error and traceback:
```
File "/poke_env/environment/pokemon.py", line 706, in pokeball
    return self._last_request.get("pokeball", None)
AttributeError: 'NoneType' object has no attribute 'get'
```

This seems to be because `self._last_request` of the Pokemon class is `None`  in that scenario, even though it should be a `dict`.

**Comment by hsahovic** [comment]
Closing this as stale, and some additional effort went into zoroark-proving this - but please reopen with a minimal reproduction script if it pops up again.
