### ISSUE TITLE
Possible documentation typo in "Cross evaluating random players" example

### ISSUE THREAD

**Issue by KierranFalloon** [hsahovic/poke-env#361]
Just a small one, but in the ["Cross evaluating random players" documentation](https://poke-env.readthedocs.io/en/stable/cross_evaluate_random_players.html#cross-evaluate-random-players), the note near the top reads: 
"_This example uses tabulate **ti** format results. You can install it by running pip install tabulate._"
Perhaps "ti" is meant to read "to"?

**Comment by hsahovic** [comment]
Good catch. I fixed it in d6b07d8 - thanks!
