### ISSUE TITLE
How to access game status using API?

### ISSUE THREAD

**Issue by SupernovaTitanium** [hsahovic/poke-env#366]
Hi, I'm new to showdown. I want to design a poke-AI using RL. However, I wonder if there exists api to access game status such as special attack boost. Then I can create a vector storing all useful attributes of the game and use it as the state in RL. 

I can't find documentation regarding how to access specific game status using api, could you tell me how to find it?

**Comment by Zachary-Fernandes** [comment]
Hello,

Yes, that should be possible with poke-env. The documentation provided goes over a max damage player as an example of a heuristics agent, but this is greedy with respect to moves' base power. I would recommend viewing the [simple heuristics player](https://github.com/hsahovic/poke-env/blob/master/src/poke_env/player/baselines.py#L15) for a more complete example of using what the API provides. The `_should_switch_out()` function checks for conditions where the current active Pokémon should switch out. On lines 77, 80, and 85, you can see how it checks how many boosts both (physical and special) defenses and attacks have. Further information on each Pokémon's details, including boosts and status, are detailed on [this documentation page](https://poke-env.readthedocs.io/en/stable/pokemon.html).

Out of curiosity, what kinds of networks/agents do you plan to develop and use? I myself am experimenting with this package for a course project, so I was wondering if we could try comparing approaches and discussing ideas.

**Comment by SupernovaTitanium** [comment]
Thank you. I now know where I can find the API to access the game attributes, I am interested in. 

Sure. I'm very happy to discuss this with you. I don't have any particular model in mind now. Maybe I can try different models and ensemble all of them. The first model would be simply using supervised learning to predict move (Probably DNN as a classifier). The second model would be using game status as state and using RL (DQN,PPO,SAC?) to learn an action network. Maybe I can implement the third model using inverse RL. The model learns a reward function by making human expert player's move has better reward than the model itself predicts. After learning the reward function, use it to train an agent. Finally, do majority vote of the three models. 

I'm afraid the model is too complicated to train though.
