### ISSUE TITLE
Implementing New Format

### ISSUE THREAD

**Issue by Zachary-Fernandes** [hsahovic/poke-env#368]
Hello, I am interested in training reinforcement learning agents to play Challenge Cup 1v1, ideally Gen 6 or Gen 9. I want to see if reinforcement learning can find an optimal decision strategy for which Pokémon to use given knowledge on their team. Would it be possible to implement this or provide instructions on how to implement a format in general? Thank you in advance.

**Comment by Kymawave** [comment]
i think you can make an agent that plays challenge cup 1v1 gen 6 out of the box, but gen 9 isnt implemented yet. from what ive seen so far, poke_env treats any given format as a string and nothing more. the showdown protocol will be the same for any format. ive made my own custom formats for training agents and poke_env really doesnt mind.

**Comment by hsahovic** [comment]
Closing as this is stale and fixed with gen9. As far as I can tell, challenge cup 1v1 is supported.
