### ISSUE TITLE
Using the AI in pokemonshowdown website

### ISSUE THREAD

**Issue by tugayapucu** [hsahovic/poke-env#371]
I am sorry if this is asked before but I have looked at the documentation and previous issues but couldn't find how to add my already trained agent to online server. Is there something I have been missing or do you guys know any additional documentation I can use.

Thank you all and have a nice day.

**Comment by Ball-Man** [comment]
I believe the related docs are under [Connecting your bots to showdown](https://poke-env.readthedocs.io/en/latest/getting_started.html#connecting-your-bots-to-showdown) and [Connecting to showdown and challenging humans](https://poke-env.readthedocs.io/en/latest/connecting_to_showdown_and_challenging_humans.html).

As explained by the pages above, bots i.e. `Player` objects accept a variety of configuration objects like `PlayerConfiguration` (to let your bot log into its own account) and `ServerConfiguration` (which contains information about the server you are connecting to).
In the latter page you can see that a server configuration for public showdown is already in the library and ready to use. The example uses `RandomPlayer`, which you should replace with a custom `Player` subclass representing your own bot.

**Comment by tugayapucu** [comment]
@Ball-Man thank you for clear explanation. I must have missed that part. Thank you again
