### ISSUE TITLE
Small Bug with reward Calculation

### ISSUE THREAD

**Issue by jweezy24** [hsahovic/poke-env#375]
When calculating the reward, the code has a bug.
Below is the code that is executed, 
```python3
for mon in battle.team.values():
    current_value += mon.current_hp_fraction * hp_value
    if mon.fainted:
        current_value -= fainted_value
    elif mon.status is not None:
        current_value -= status_value

current_value -= (number_of_pokemons - len(battle.team)) * hp_value #BUG HERE
```
The line ` len(battle.team)` will always be 6. Thus, causing the bug.

**Comment by Kymawave** [comment]
i have no idea how the calc reward function works, but ive verified it works correctly on many occasions. i dont think this is a bug.

**Comment by jweezy24** [comment]
So whats the point of the last line if it will always be 0? Below it, the opponent's case, it changes relative to how many mons are active. I assumed that it was the intended purpose here?

**Comment by hsahovic** [comment]
`len(battle.team)` and `len(battle.opponent_team)` are not necessarily 6.
The two main situations where this is relevant:

- your team comprises less than the max number of Pokemon the format authorizes. This would effectively treat the missing mons are fainted mons in reward calculation
- you have not seen some of the opponent's team yet. You can usually safely assume that it has `number_of_pokemons` pokemons (although that might be wrong)

Closing this for now, feel free to tag me if I missed something.
