### ISSUE TITLE
Gen9 integrations

### ISSUE THREAD

**Issue by GiacomoAru** [hsahovic/poke-env#377]
# Will the library be updated with gen9 additions?

## I'm interested in the API as it would be a perfect base for a personal project I want to undertake, and I've seen the branch with gen9 integrations.  I'm not an expert on GitHub so I'm not sure if or how it will be integrated into the standard library that you download with the usual "pip install", that's why I'm asking.

**Comment by Ball-Man** [comment]
Hi,
as you have seen, the branch is there and is being updated weekly. I am not in direct contact with @hsahovic (the maintainer), but I can assume that as soon as it is working and tested it is going to be integrated.

A couple of interesting facts. You can pip install a github repository with the command:
```
pip install git+repository-url
```
For example, you can install `poke-env` in this way:
```
pip install git+https://github.com/hsahovic/poke-env
```
This is similar to `pip install poke-env`. However, installing directly through the repository gives you access to latest updates that have not been pushed to the official pip index yet. Of course this exposes you to potentially experimental and dangerous features, but you can also use it to comfortably preview some updates.

The command above would install the latest commit from master/main branch, but it can also be done for specific branches by adding `@branch-name`. For example, you can install the gen9 branch with:
```
pip install git+https://github.com/hsahovic/poke-env@add-gen-9-support
```
Be aware that the branch is **almost certainly still broken** so you may get nothing out of it, but it is still worth a try.

Sorry for the delayed response.
