### ISSUE TITLE
Player limit issue

### ISSUE THREAD

**Issue by uduse** [hsahovic/poke-env#38]
My classmate and I did a [course project on generating Pokemon-playing scripts](https://github.com/dem1995/pokemon-evolutionary-agents) using your library. The biggest issue we encountered during the development process is the player limit. Initially, we wrap every single script into a player, and as more players join, the server just hangs for some reason (around 4000 players). We were not sure if the problem is caused by poke-env or PS. We tried `del` the players and force garbage collection, but the problem still persisted. The way we solved it is by creating a shared pool of say 500 players, splitting battle tasks in chunks, and assign specific battle tasks to available players. I feel like this issue should at least be mentioned in the documentation, or throwing error message when there are too many players, or supporting creating a pool of players.

**Comment by hsahovic** [comment]
Hi @uduse ! Thanks for reporting this issue. I have to admit that I did not really had in mind an approach requiring several thousands agents, and I'm actually quite excited to see that you tried it out!

When you say that it hangs, is it just paralyzed or is it throwing errors?

Could you share the code you came up with for pools? I'd like to see how you implemented it, and evaluate if it should be added to the current library.
Furthermore, it would be useful if you have an example to reproduce the issue. Thanks!

**Comment by uduse** [comment]
Full example can be found [here](https://github.com/dem1995/pokemon-evolutionary-agents/blob/master/sandbox.ipynb). The function that matters is `evaluate_population`, where a `population` is a collection of scripts (battle logics) to be evaluated.

**Comment by hsahovic** [comment]
I'm going to close this issue for now; performance optimization is on the project's roadmap, and I will test scalability when we start working on it.
