### ISSUE TITLE
check_env problem 

### ISSUE THREAD

**Issue by KlausRyu** [hsahovic/poke-env#382]
I was start to try debug the reinforcement learning example, but i get this error, is it gym problem or it is the code bug.

![Capture1](https://github.com/hsahovic/poke-env/assets/58900577/b7f1c041-9d6d-4570-ae75-a983b9922f7d)

**Comment by KlausRyu** [comment]
solved by downgrade from 0.26 to <0.26

**Comment by KlausRyu** [comment]
and i get error.
![Capture2](https://github.com/hsahovic/poke-env/assets/58900577/0362ccfb-5c10-4467-b2c6-4d87e5a8f684)

**Comment by cameronangliss** [comment]
@hsahovic I believe this issue is resolved, do you agree?

**Comment by hsahovic** [comment]
Yes - good catch @cameronangliss
