### ISSUE TITLE
Revival blessing causes many issues. 

### ISSUE THREAD

**Issue by kodecreer** [hsahovic/poke-env#386]
Hi I figured out how to get my environment working with revival blessing with only one time update. It's super weird, but I first send a request of the move then I have to return a request of the pokmeon I want to choose. The main issue however comes up whenever there are two in a row.

**Comment by hsahovic** [comment]
Hi @kodecreer,
Thanks for opening this issue. Do you have a minimal script I could use to reproduce this issue?

**Comment by kodecreer** [comment]
This was fixed in the update and in the fork I put in.
