### ISSUE TITLE
gen-9 doubles and custom-game support request

### ISSUE THREAD

**Issue by TimelessMemorial** [hsahovic/poke-env#410]
Hello!

I need gen-9 doubles and custom game support (if it hasn't been supported already) I'm interested in assisting to work towards that if necessary. (I'm willing to add the implementations myself with a little guidance as necessary as it would help me better understand how poke-env functions)  

I have experience working on my own personal projects, but this would be my first time collaborating with others! This support would be useful for my own personal project and I'm not afraid to work for it if I need to!

**Comment by hsahovic** [comment]
Hey @TimelessMemorial - have you tried running such a game with poke-env? I suspect it might work out of the box

**Comment by hsahovic** [comment]
Closing as stale, and probably already working. Feel free to reopen if necessary.
