### ISSUE TITLE
`cross_evaluate` isn't functioning properly

### ISSUE THREAD

**Issue by cameronangliss** [hsahovic/poke-env#431]
IMPORTANT: This issue arose on the most recent commit of `poke_env`, which is as of now unreleased, so this issue may not be present in the officially-released version.

I made two instances of my `Agent` class which inherits the `Player` class from `poke_env`:
```
player_configuration = AccountConfiguration(config["username"], config["password"])
opponent_configuration = AccountConfiguration(config["alt_username"], config["alt_password"])
player = Agent(player_configuration)
opponent = Agent(opponent_configuration)
```
I then proceeded to attempt to run 100 battles between these two agents:
```
results = await cross_evaluate([player, opponent], 100)
```
When running this line, the runtime freezes indefinitely after the first battle has finished. As the first battle is beginning, I get the following warning from the logger in my terminal:
```
WARNING - Popup message received: |popup|You challenged less than 10 seconds after your last challenge! It's cancelled in case it's a misclick.
```
I believe the issue may lie in this segment of code from within `cross_evaluate`, in which multiple challenges are made at once without waiting for the first battle to finish:
```
await asyncio.gather(
    p_1.send_challenges(
        opponent=to_id_str(p_2.username),
        n_challenges=n_challenges,
        to_wait=p_2.ps_client.logged_in,
    ),
    p_2.accept_challenges(
        opponent=to_id_str(p_1.username),
        n_challenges=n_challenges,
        packed_team=p_2.next_team,
    ),
)
```
Further evidence for this theory is that I tried the following altered line, and I experienced neither the runtime freeze nor the warning from the logger (the difference is that I replaced 100 with 1):
```
results = await cross_evaluate([player, opponent], 1)
```
I would like to be able to use the `cross_evaluate` function if I could, but as-is, it appears to not work for `n_challenges > 1`. Any help would be appreciated :)

**Comment by hsahovic** [comment]
I was not able to reproduce locally. Are you running your showdown server with the `--no-security` flag set?

**Comment by cameronangliss** [comment]
Ah, I think I see the problem. I was running with `server_configuration=ShowdownServerConfiguration` in my Agent instances, which connects them to the actual PS website. I suppose `cross_evaluate` isn't intended to be used in such a way?

**Comment by hsahovic** [comment]
The main showdown server has several rate limiting measures in place - as far as i know they are friendly to bot developers, but they don't want hundreds of bot battles to happen on their main server, as it's not its purpose. I would only use bots on the main server for testing after development, and only at a reasonable rate (a couple of concurrent battles).

**Comment by cameronangliss** [comment]
Alright, thanks! Closing now.
