### ISSUE TITLE
Exposing the battle logs in the Battle object to support LLM agents.

### ISSUE THREAD

**Issue by SirSkaro** [hsahovic/poke-env#502]
I've noticed there have been a few attempts to create LLM agents using this `poke-env`. A more recent one is [PokeLLMon](https://github.com/git-disl/PokeLLMon). However, in their project (not saying I condone this at all), they literally copy/pasted all of `poke-env` to modify `Player` to get access to the Showdown message. 

A more appropriate, less drastic approach would be to extend `Player` and override `_handle_battle_message` (or some other internal function), but this obviously isn't ideal either because you're overriding an internal function.

So this is a feature request is to add the raw Showdown message to the `Battle` object (the `battle_info` or `split_messages` data in `Player#_handle_battle_message`) to better support LLM agents.

**Comment by caymansimpson** [comment]
Nice, was going to ask for this one as well. @hsahovic is there any way you'd like to do this? I was thinking about just adding a flag that stores all unparsed logs in a vector of strings as a property of the battle object

**Comment by caymansimpson** [comment]
This is submitted in the new PR. You can check out the new battle.observations property. Battle Logs are stored in the events property of each Observation object

**Comment by hsahovic** [comment]
Thanks @caymansimpson !
