### ISSUE TITLE
VGC support -- add a battle property for your sent team

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#521]
Right now, once you choose your team from teampreview, you don't have a way to access the 4 mons you've chosen. I'd like to add a property to the Battle object to store this information. Do you have a preference of what property this is called? (e.g. sent_team, chosen_team, etc)

**Comment by hsahovic** [comment]
Ideally, I would like this to be stored in the regular `team` attribute, while your full team (including non-selected ones) is stored somewhere else.

**Comment by caymansimpson** [comment]
Closing this to merge with #522
