### ISSUE TITLE
Obtaining Valid doubles moves

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#524]
There is a function in singles to obtain all valid moves for random player, but a similar one doesn't exist for doubles. I think it would be great to:
1. Add this functionality into Player
2. Add a function in Battle that validates whether an order will return an error (eg battle.is_valid_order(order))
3. Add a function in BattleOrder that validates whether an order is valid given a battle (eg order.is_valid(battle))

**Comment by hsahovic** [comment]
I think this makes sense. For `2.`, what about automatically validating all double orders?

**Comment by caymansimpson** [comment]
Sounds like a great idea! How/where would you recommend doing that?

**Comment by hsahovic** [comment]
Yeah potentially - although I'm not sure what the value is, now that I think about it. If you `choose_move` implementation is wrong, raising an exception will probably not help.

**Comment by caymansimpson** [comment]
Hm, thinking about it, you're right.

My initial motivation was to use it to help my AI -- eg my networks and/or algorithms are going to choose a distribution of probabilities over actions, and I'd like to 0 out each invalid action, and SoftMax the rest to get the probability to take each valid action.

Given this, I think there's two ways we could do this:
1. Add this functionality into battle (`battle.is_valid(order: BattleOrder) -> bool`) -- this will also require us to add an optional actor into `battle_order`, which will be relevant specifically for doubles (unless it's assumed that `first_order` `is battle.active_pokemon[0]`)
2. Implement this as a separate utility in my bot outside of poke-env

Do you have a preference?

**Comment by caymansimpson** [comment]
OK -- Im finished writing the validation method in DoubleBattleOrder and BattleOrder, and I'm wondering how you would prefer me to write unittests?

I ask because across both, there's ~40 checks to do to ensure a move isn't valid. There's a couple of problems I'm running into:
1. Recall -- I think the problem with this method is that it will be hard to understand whether I am over-enforcing on validity without an absurd amount of unittests asserting `is_valid() == true`. 
2. Unittests -- do you want me to add all ~51 different scenarios to test against to ensure that each case is valid? 
3. Does poke-env handle Zoroark well? I don't have special cases for it yet, and wondering whether I should add them 

Informally, I'm going to just run a bunch of edge case teams (and random doubles) against each other thousands of times to ensure that nothing gets through across formats, but wondering how much I should add to the unit tests

**Comment by hsahovic** [comment]
I think you can ignore Zoroark.

For the 40 checks, I think they will be required for this to make sense.

**Comment by hsahovic** [comment]
Have you looked at `DoubleBattleOrder.join_orders`? I suspect it might do a lot of what you are looking for

**Comment by caymansimpson** [comment]
Yeah, I think the annoying part is that I have to consider many conditions, so I will have to simulate many different battle states via requests to capture them all. But thanks for the guidance -- Ill add these in and submit a PR once Im finished!

**Comment by hsahovic** [comment]
That makes sense. I that case, let's close it :)
