### ISSUE TITLE
Add heuristic/Max damage support for doubles

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#526]
Since these are available for singles, it would be great to add these for doubles. With:
1. is_valid and get_all_doubles_moves, random would be easy to implement
2. target_types and better showdown --> poke-env array conversions, maxdamage would be easy to calculate too

eg https://github.com/caymansimpson/reuniclusVGC/blob/main/bots/max_damage_player.py and https://github.com/caymansimpson/reuniclusVGC/blob/main/bots/random_doubles_player.py

**Comment by hsahovic** [comment]
What do you have in mind for better PS -> Poke-env conversions?

**Comment by caymansimpson** [comment]
I've documented the behavior of this problem [here](https://github.com/caymansimpson/poke-env-old/blob/d52ab187c1b74d1e1670bfcec28544d8dd5f927b/src/poke_env/utils.py#L90) and added this helper to address these issues.

My implementation is not ideally integrated I'm pretty sure and I'm not really sure how to do this "correctly". I was thinking maybe an abstraction where we convert BattleOrder targets to showdown targets? But I am so not confident in my assessment

**Comment by caymansimpson** [comment]
Haha I think whatever we decide here: https://github.com/hsahovic/poke-env/issues/523

Then we can just implement something basic like this: https://github.com/caymansimpson/reuniclusVGC/blob/main/bots/max_damage_player.py

**Comment by caymansimpson** [comment]
Andre submitted these iiuc
