### ISSUE TITLE
VGC open/deny team sheets & Medal Messages

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#530]
There are two things poke-env can't handle right now in Showdown:
1. In VGC Regulation F, you can accept or reject having open team sheets. poke-env throws errors because it doesn't know how to parse this request and also doesn't have functionality to let you interact.
2. Showdown gives some messages to promote it's ladder seasons

poke-env doesn't know how to parse these and raises a `NotImplementedError`

**Steps to repro**: create a battle with two random players using `format="gen9vgc2024regg"`

Offending code: [Line 754 of abstract_battle.py](https://github.com/caymansimpson/poke-env/blob/627b79ea20c85ad7990fcce04711181646600672/src/poke_env/environment/abstract_battle.py#L754)

The two split_messages that aren't handled:
1. ['', 'uhtml', 'otsrequest', '<button name="send" value="/acceptopenteamsheets" class="button" style="margin-right: 10px;"><strong>Accept Open Team Sheets</strong></button><button name="send" value="/rejectopenteamsheets" class="button" style="margin-top: 10px"><strong>Deny Open Team Sheets</strong></button>']
4. ['', 'uhtml', 'medal-msg', '<div class="broadcast-blue">Curious what those medals under the avatar are? PS now has Ladder Seasons! For more information, check out the <a href="https://www.smogon.com/forums/threads/3740067/">thread on Smogon.</a></div>']

**Comment by hsahovic** [comment]
`uhtml` messages are [currently ignored](https://github.com/hsahovic/poke-env/commit/edab34e81b3716271312b3531c51f27c02935556). I'm unsure what that would result in for open team sheet messages. I assume they will just never be accepted?
If you want to implement it, I think it would make sense to have a parameter in `Player` object to define whether to accept open team sheet proposals.

**Comment by caymansimpson** [comment]
Closed this in the PR that I mentioned above
