### ISSUE TITLE
Logging final reward for interval

### ISSUE THREAD

**Issue by thatCode-Psy** [hsahovic/poke-env#55]
I am looking for a way to grab the final average reward of an interval to be used for graphing performance over time. Looking through the code I do not see anything that returns that specific value without manually calculating from each time reward is calculated.

**Comment by hsahovic** [comment]
Thanks for opening this issue! There is currently no built-in utility to compute the average reward per episode.

You could either:

- Compute it manually during training (I suppose that some RL frameworks also do this automatically for you)
- Implement a suitable mechanism in `poke-env` directly. If you were to do this, do not hesitate to open a PR!

If you want, I can provide an example training function to compute the average reward, or give you pointers towards implementing it in the repo.

**Comment by hsahovic** [comment]
I'm going to let this issue open a couple more days.

**Comment by thatCode-Psy** [comment]
Whoops, I forgot to post that I decided to go with the former solution and got that implemented.
