### ISSUE TITLE
[Proposal] Replace `gymnasium` with `pettingzoo`

### ISSUE THREAD

**Issue by acxz** [hsahovic/poke-env#560]
Pokemon battles are fundamentally a multi-agent system.

Currently we are using [Farama's](https://farama.org/) [Gymnasium](https://gymnasium.farama.org/) which is a RL env API for _single-agents_. I believe this decision came about as at the time of this project's creation there was no standard/popular multi-agent RL env API, leaving us to choose [OpenAI's](https://openai.com/) [Gym](https://github.com/openai/gym), which has now moved over to Gymnasium.

However, with popularity rising in multi-agent systems, various RL env API's have been created for multi-agent systems, such as Farama's [PettingZoo](https://pettingzoo.farama.org/) and Google Deepmind's [OpenSpiel](https://github.com/google-deepmind/open_spiel) among others.

Overall, PettingZoo has become a strong defacto for _multi-agent_ systems as it closely resembles Gymnasium's API, is mathematically more general than the other RL multi-agent env APIs, and more importantly has seen adoption in the popular RL libraries such as [rllib](https://pettingzoo.farama.org/tutorials/rllib/), [tianshou](https://pettingzoo.farama.org/tutorials/tianshou/), [stable-baselines3](https://pettingzoo.farama.org/tutorials/sb3/), among others.

With this in mind, and again recognizing that Pokemon battles are a _multi-agent_ system, I believe that we should be using `pettingzoo` instead of `gymnasium`.

Practically, this would mean a change in the API for us and it should mean that certain logic we may have assumed/worked around due to using a single-agent API would be simpler in PettingZoo's API.

I'd love to hear everyone's thoughts about this and the feasibility of this change. I truly believe such a change would increase the usability of this project.

**Comment by hsahovic** [comment]
This sounds like a good idea, and I would be open to discussing a plan to implement it.

**Comment by acxz** [comment]
Nope never started actually implementing it. Knock yourself out.

**Comment by caymansimpson** [comment]
@acxz I saw your recent PR on #1! And a few of us have been talking about how to do #2 [here](https://docs.google.com/document/d/1eEAdA-ZZo6Y0NEFP47Ei87JiEJqVYNSHaszqabhJ4nc/edit?tab=t.0)! Would love your thoughts and comments, or if you've already started thinking about this, to understand what you've been up to/planning. 
None of us have been able to prioritize it (or are planning to atm) -- and so are just trying to get a lay of the land, thoughts on approaches and figure out who can take a first crack at this. If you comment on it w/ your contact info (like a linkedin or smth), we could start a chat or smth

**Comment by hsahovic** [comment]
I'm going to close this as the title issue has been solved - feel free to continue chatting here, in discussions, on discord or in a new issue, as you prefer.

**Comment by cameronangliss** [comment]
@acxz all done!
