### ISSUE TITLE
Invalid authentication tokens and Unimplemented error

### ISSUE THREAD

**Issue by cjyu81** [hsahovic/poke-env#62]
When running cross_evaluate_random_players, I initially received the invalid authentication token error. I thought this was an error with the default random player accounts so I replaced them with accounts I registered myself. I edited the file as shown below

`
#players = [RandomPlayer(max_concurrent_battles=10) for _ in range(3)]

players =[RandomPlayer(player_configuration=PlayerConfiguration("validusername1","validpassword"),max_concurrent_battles=10),
        RandomPlayer(player_configuration=PlayerConfiguration("validusername2", "validpassword"),max_concurrent_battles=10),
        RandomPlayer(player_configuration=PlayerConfiguration("validusername3", "validpassword"),max_concurrent_battles=10)]
   `
However now instead of getting three authentication token errors, I get this error three times(with a different battle each time):

2020-08-17 17:20:41,790 - snivyagent1771 - ERROR - Unhandled exception raised while handling message:
>battle-gen8randombattle-12
|player|p2|snivyagent1771|266|
|teamsize|p1|6
|teamsize|p2|6
|gametype|singles
|gen|8
|tier|[Gen 8] Random Battle
|rule|Species Clause: Limit one of each Pokémon
|rule|HP Percentage Mod: HP is shown in percentages
|rule|Sleep Clause Mod: Limit one foe put to sleep
|
|t:|1597684841
|start
|switch|p1a: Wigglytuff|Wigglytuff, L88, M|100/100
|switch|p2a: Rotom|Rotom-Heat, L80|211/211
|-item|p2a: Rotom|Heavy-Duty Boots|[from] ability: Frisk|[of] p1a: Wigglytuff|[identify]
|turn|1
Traceback (most recent call last):
  File "/home/charliejyu88/poke-env/src/poke_env/player/player_network_interface.py", line 152, in _handle_message
    await self._handle_battle_message(message)
  File "/home/charliejyu88/poke-env/src/poke_env/player/player.py", line 255, in _handle_battle_message
    battle._parse_message(split_message)
  File "/home/charliejyu88/poke-env/src/poke_env/environment/battle.py", line 415, in _parse_message
    raise NotImplementedError(split_message)
NotImplementedError: ['', 't:', '1597684841']

I am unsure of how I can work around/fix this problem

**Comment by hsahovic** [comment]
Hey @cjyu81,

Thanks for opening this issue.

Are you trying to connect to showdown's servers, a local custom server or the recommended optimized server?

Are you passing a custom `ServerConfiguration` object?

**Comment by cjyu81** [comment]
I am trying to connect is to a local server(localhost:8000). I have not edited ServerConfiguration

**Comment by hsahovic** [comment]
Are you running [smogon's](https://github.com/smogon/pokemon-showdown) version of showdown or [this one](https://github.com/hsahovic/poke-env)?

**Comment by cjyu81** [comment]
I have been running smogon's version with the "node pokemon-showdown" command. How do I run your version of the showdown server?

**Comment by hsahovic** [comment]
@cjyu81 you can follow [these instructions](https://poke-env.readthedocs.io/en/stable/getting_started.html#configuring-a-showdown-server) to setup the custom server: the main difference with the official server is that it gets rid of a lot of rate limiting, so you can run hundreds of battles per minute.

That being said the examples should work with the official implementation if you are using authentication. I'll take a deeper look at it tonight: I suspect that the `t` messages (eg. `|t:|1597684841` from above) were introduced fairly recently, and are the root cause of the issue.

**Comment by cjyu81** [comment]
Running your version of showdown fixed the problem. Thank you for the help!

**Comment by hsahovic** [comment]
Great, I'm glad it fixed your issue! I'll take a deeper look at this though, as it might have a deeper cause.

**Comment by hsahovic** [comment]
It looks like showdown added `t` messages in battles; PR #63 should fix this issue.
