### ISSUE TITLE
-singlemove handling

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#623]
In battle.parse_message handling, we erroneously ignore -singlemove, so we don't record effects like Destiny Bond/Glaive Rush/Grudge/Rage. I plan to submit a PR to just remove this from MESSAGES_TO_IGNORE and also add a test

**Comment by hsahovic** [comment]
Fixed by https://github.com/hsahovic/poke-env/pull/633
Thanks @caymansimpson !
