### ISSUE TITLE
Replacing rquid with last request

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#624]
In the abstract_battle object, we store rqid, but say not to use it. Instead of storing rqid, I propose storing the entire last_request. This will contain the last rqid, but also retain all information in the last request. This will be useful for those keeping parallel battle states (eg if we want to maintain an abstracted battle that we can pass to another engine, or for inferences)

**Comment by hsahovic** [comment]
Fixed by https://github.com/hsahovic/poke-env/pull/634
Thanks @caymansimpson !
