### ISSUE TITLE
Add name property to Pokemon

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#625]
You can add nicknames to pokemon in-game (or in sowdown) which will become their showdown identifier. I am adding this as a field to the Pokemon class so that given a Pokemon, we can reconstruct its showdown identifier. This helps with battle parsing

**Comment by hsahovic** [comment]
Fixed by https://github.com/hsahovic/poke-env/pull/638
Thanks @caymansimpson !
