### ISSUE TITLE
Remove direct editing of split_message in parse_message

### ISSUE THREAD

**Issue by caymansimpson** [hsahovic/poke-env#627]
In abstract_battle.parse_message, poke-env edits the split_message directly. This creates undesired behavior if following methods upstream try to use the same split_message, since we edit it within the parse_message function.

I will copy the split_message before we edit it, so that there's no unexpected handling of the battle logs for any downstream consumers of them

**Comment by hsahovic** [comment]
Fix by https://github.com/hsahovic/poke-env/pull/641 - thanks @caymansimpson !
