### ISSUE TITLE
A number of errors in the code

### ISSUE THREAD

**Issue by henrycharlesworth** [hsahovic/poke-env#7]
Hi, firstly I just wanted to say great job with this project, I'd been contemplating trying to train a reinforcement learning AI to learn Pokemon battling but diving into the Pokemon showdown code directly was a bit intimidating - so I'm really glad to have found this project!

I just thought I'd let you know that I've found a few small bugs so far whilst studying the moves.py file (all are easy fixes). Firstly, the self_boost method is incomplete - there are actually only two moves in the json file that have a "selfBoost" entry, and lots of others that have a "self": { "boosts": {...}} entry that is ignored in your implementation (e.g. close combat, leafstorm)

Secondly the status method is incorrect, it should return `Status[self.entry["status"].upper()]` but it has Status(...) - i.e. brackets instead of [ ].

Then there are similar errors that I've noticed with the drain, heal, recoil and n_hit methods. In drain you have `self.entry["drain"][0] / self.entry["drain"][1]` - there should be speech marks around the 0 and the 1. This is also true for heal. Similarly for recoil you have `self.entry["recoil"] / self.entry["recoil"][1]` and this should be `self.entry["recoil"]["0"] / self.entry["recoil"]["1"]`. Then with n_hit it's wrong because `self.entry["multihit"]` is never a list but can be an integer or a dictionary

**Comment by henrycharlesworth** [comment]
Another one: in move.accuracy - if it's "true" then this still registers as an int, and so it gets divided by 100 and returns 0.01.

**Comment by henrycharlesworth** [comment]
One more: ignoreImmunity isn't always true or false, there is one move (thousandarrows) where it returns "Ground" - probably not very important but still

**Comment by hsahovic** [comment]
Hi Henry,

Thanks for the report!
I'll start working on these bugs asap, unless you prefer opening a PR yourself. If you find others, please continue reporting them!

**Comment by hsahovic** [comment]
#8 fixes the bugs you reported so far. I will keep it open for some time before merging it, in case other bugs are reported in the next couple of days.

**Comment by hsahovic** [comment]
I've added tests for the whole `move.py` file. I'm closing the issue, merging #8 and pushing a new version to Pypi - release 0.0.3.
