### ISSUE TITLE
Running the RL code: element not in graph

### ISSUE THREAD

**Issue by pablovin** [hsahovic/poke-env#75]
Hi there!

Thanks for this great resource, it looks super nice!

I am trying to run the " rl_with_open_ai_gym_wrapper.py " code, but I am facing this error:

ValueError: Tensor Tensor("dense_2/BiasAdd:0", shape=(None, 22), dtype=float32) is not an element of this graph.

I am running it with the newest tensorflow-gpu version and the keras-rl2

Any idea what this might be?

Cheers,

Pablo

**Comment by hsahovic** [comment]
Hey @pablovin,

Thanks for opening this issue. We had some issues with keras-rl versions, and I suspect that this is what you're up against. Updating the examples with another RL library is planned.

Can you try installing version `1.0.3` of keras-rl (`pip install keras-rl==1.0.3`)?
If that does not work, let me know and please add a `git freeze` export.

Best,
Haris
