### ISSUE TITLE
Having trouble running the agent

### ISSUE THREAD

**Issue by mancho1987** [hsahovic/poke-env#76]
Hi,

When I run rl_with_open_ai_wrapper.py I get  TypeError: len is not well defined for symbolic tensors. Please call 'x.shape' rather than 'len(x)'.
I tried changing tf versions but can't make it work.

**Comment by hsahovic** [comment]
Hi @mancho1987,

Thanks for opening this issue.
I suspect that you are facing something similar to #75, with maybe a tensorflow version issue on top of it.
Can you try installing `keras-rl2==1.0.3`, updating you tensorflow version and see how it goes?

**Comment by mancho1987** [comment]
Thanks, that worked! Wish I could have solved it so easily, was trying for quite a bit haha :)
