### ISSUE TITLE
Not Implemented Error when playing against humans

### ISSUE THREAD

**Issue by pablovin** [hsahovic/poke-env#79]
Hi,

I am trying to connect an agent to play against humans. The function: player.send_challenges is not working, but the accept_challenges works nicely.

When the battle starts, tho, I get this error message:

Traceback (most recent call last):
  File "/home/pablo/Documents/Workspace/PokeEnvGYM/venv/pokegym/lib/python3.6/site-packages/poke_env/player/player_network_interface.py", line 152, in _handle_message
    await self._handle_battle_message(message)
  File "/home/pablo/Documents/Workspace/PokeEnvGYM/venv/pokegym/lib/python3.6/site-packages/poke_env/player/player.py", line 255, in _handle_battle_message
    battle._parse_message(split_message)
  File "/home/pablo/Documents/Workspace/PokeEnvGYM/venv/pokegym/lib/python3.6/site-packages/poke_env/environment/battle.py", line 415, in _parse_message
    raise NotImplementedError(split_message)
NotImplementedError: ['', 't:', '1603136853']

If I run it again, the third value of the array varies: [1603137047, 1603137081], and so on.

Any chance you would know what is happening?

Cheers,

Pablo

**Comment by hsahovic** [comment]
Hi @pablovin,

Thanks for opening this issue.
The latest release of poke-env is not up to date with showdown. That wouldn't have been a problem in most situations; however, showdown recently introduced a couple of protocol updates which are causing the issue you are encountering.
I have a local version of poke-env that's compatible with this updated protocol. My plan was to wait for the doubles PR to be merged before including it, but I'm going to merge it earlier if it's causing problems.
I'll do that tomorrow - your code and model should be fully compatible with this update.

Best,
Haris

**Comment by pablovin** [comment]
Hi @hsahovic,

thanks for the prompt response!
I got it. Let me know when I can update on my end.

Cheers,

Pablo

**Comment by hsahovic** [comment]
Oops, didn't mean to close the issue.

**Comment by hsahovic** [comment]
I wanted to get this done today but I'll need to update all the underlying data files too (pokedex + moves), which I was not expecting. I'll try to do that tomorrow.

**Comment by hsahovic** [comment]
Version 0.3.7 is out and should solve your issue :) Update with `pip install poke-env==0.3.7` and let me know if everything works as expected!

**Comment by pablovin** [comment]
Hi Haris,

It works like a charm! Thank you so much for taking the time to check this out!

cheers,

Pablo
