### ISSUE TITLE
moltresgalar isn't listed in Pokedex

### ISSUE THREAD

**Issue by Jay2645** [hsahovic/poke-env#84]
Seems like data/pokedex.json is missing an entry for moltresgalar and it's causing crash bugs whenever a game is started with Galarian Moltres in the list of Pokemon.

Is there a command I can run locally to force-fetch the Pokedex from the Showdown repo and have the .json files automatically placed in the proper locations? I see there's something along those lines in the `scripts` directory, but looks like it just outputs to `out.json` and not to the proper locations (not that it's the end of the world).

**Comment by hsahovic** [comment]
Hey @Jay2645,

Thanks for opening this issue. Yep, the current data files are [a couple days old](https://github.com/hsahovic/poke-env/commit/4e7cdf04a5f2f8470097ab9057e5e5ce8eaa5ce1) and have not been updated with showdown's latest releases. I was planning on updating them this weekend, but you can indeed use the scripts you found to do that manually (they output `out.txt` to allow comparisons before merging, but you can copy-paste their output in place of the data files and things should run fine).

If you don't care about the latest releases, you can also use `poke-env` with [this version](https://github.com/hsahovic/Pokemon-Showdown) of showdown, which is optimized for performance (but does not provide human players).

Let me know if you encounter any other issue!

**Comment by hsahovic** [comment]
This should be fixed by release `0.3.9` :)
