### ISSUE TITLE
What packages are needed to run rl_with_open_ai_gym_wrapper.py?

### ISSUE THREAD

**Issue by Jay2645** [hsahovic/poke-env#85]
To be specific, I'm running on Windows and I'm mostly curious what versions to use for the different imports in `rl_with_open_ai_gym_wrapper.py`.

`pip install rl` fails to even install on Windows due to requiring `sys/time.h`, which only exists on Linux. The replacement seemed to be `keras_rl`. 

I initially was using Tensorflow 1.15.4, but I started getting `'tensorflow._api.v1.random' has no attribute 'set_seed'` when calling `tf.random.set_seed(0)`, which prompted me to upgrade to Tensorflow 2.

However, `keras_rl` doesn't work on Tensorflow 2 -- failing with ["len is not well defined for symbolic tensors"](https://github.com/keras-rl/keras-rl/issues/348). There's a version without that bug, `keras_rl2`... which comes _so close_ to working, but then fails with `Tensor Tensor("dense_2/BiasAdd:0", shape=(None, 22), dtype=float32) is not an element of this graph` when calling `dqn.fit`.

I'm going to keep trying different combinations -- but it'd be nice somewhere if there was a comment saying what versions it's designed to work with. :)

**Comment by hsahovic** [comment]
Hi @Jay2645,

Thanks for opening this issue. As mentioned in [the docs](https://poke-env.readthedocs.io/en/stable/rl_with_open_ai_gym_wrapper.html), the `rl_with_open_ai_gym_wrapper.py` example recommends using `keras-rl2==1.0.3` with `tensorflow 2.X`.
I think some users have tested it on windows, so it should be fine :) Let me know if it works!

**Comment by Jay2645** [comment]
Hmm -- using `keras-rl2==1.0.3` and the version of Tensorflow it installs (`tensorflow==2.0.0b1`), I'm running into this error when compiling the dqn: `'tuple' object has no attribute 'layer'`. Seems to be a Tensorflow bug. I'll keep digging around to see if I can fix it on my end -- I'm sure there's something I'm probably missing.

**Comment by Jay2645** [comment]
Ah! Knew it was something stupid. I was using `keras.layers` instead of `tensorflow.keras.layers`. Closing.
