### ISSUE TITLE
Possibility of cloning a battle state so that we can use planning algorithms

### ISSUE THREAD

**Issue by henrycharlesworth** [hsahovic/poke-env#9]
I was just wondering whether there is a way the environment can be modified so that we can save and reload the state of a battle? My current plan is to try and train a reinforcement learning agent which won't need this feature, but in the future I think being able to add planning on top (e.g. MCTS) is likely to make the agent a lot stronger. However, to do this you need to be able to clone the current battle state multiple times and try out different action sequences in order to make a single decision. This seems like it could be tricky as I assume you'd have to mess with the Pokemon showdown code a bit - but it would be an incredibly useful feature if you could think of a way.

**Comment by hsahovic** [comment]
This would definitely be an interesting and valuable feature, but I think that for now it is outside of the scope of this project. As you mentioned, it would require significant meddling with showdown's code.
Maybe open an issue on showdown and see what the feedback is on their side?

I'm closing it for now.
