### ISSUE TITLE
Publication 

### ISSUE THREAD

**Issue by pablovin** [hsahovic/poke-env#93]
Hi Haris,

I am preparing a publication where I use the environment to evaluate a personalization scheme for RL. Do you have any publication I can cite for the environment and/or baseline results?  

Otherwise, I would link the github page. 

Cheers,

Pablo

**Comment by hsahovic** [comment]
Hi @pablovin,

Thanks a lot for this proposal! As this project is still under development, there's no paper to cite yet.

I would suggest something like this, if this works on your end:

```bibtex
@misc{poke_env_2020_11_14,
    author       = {Haris Sahovic},
    title        = {Poke-env: pokemon AI in python},
    version      = {0.3.10},
    url          = {https://github.com/hsahovic/poke-env}
}
```

**Comment by pablovin** [comment]
Hi Haris,

Awesome! It works greatly! I will finish the paper up and if you want, I can share it here with you later on.

Thanks again for this great environment :)

Cheers,

Pablo

**Comment by hsahovic** [comment]
Thank Pablo! I'd love to read it when it's ready :)
