### ISSUE TITLE
Opponent pokemon have no stat values

### ISSUE THREAD

**Issue by mancho1987** [hsahovic/poke-env#94]
Hey Haris,

I wanted to use as features the stat values of both the agent mons and the opponent mons, but the opponent mons have no stat values. Then I tried with the base stats, which they do have, but their level always shows 100 and not the actual one, so I couldn't make the calculations of their stats.

**Comment by hsahovic** [comment]
Hey @mancho1987,

Thanks for opening this issue.
For `stats`, it makes sense: we don't have access to the opponent's stats; I plan on integrating some logic to try to deduce them, but it won't happen anytime soon. `baseStats` should be accurate; I'll investigate for `level` and try to push a fix tonight.

**Comment by hsahovic** [comment]
This should be fixed by version `0.3.11`. Let me know if it works on your end!

**Comment by mancho1987** [comment]
Thanks, I'll check it a bit later and let you know :) 
About stats, its true, but maybe for random battles a reasonable assumption could be made? If I am not mistaken, almost every set is a neutral nature and 85 evs in each stat, then the formula is quite simple

**Comment by mancho1987** [comment]
Tried it and it works, thanks 👍

**Comment by hsahovic** [comment]
Great! I'm closing :)

Regarding stats, that's an option - that being said, I won't implement stats deduction before at least a couple of weeks.
