### ISSUE TITLE
Loading RL Agent from saved model

### ISSUE THREAD

**Issue by abhilashpandurangan** [hsahovic/poke-env#96]
Is there any way to load RL player from saved model?

**Comment by hsahovic** [comment]
Hi @abhilashpandurangan,

Thanks for opening this issue.
Saving and loading RL models will take different forms depending on the framework you are using.

If you are referring to the example in the documentation (which uses `keras-rl`), you can use [`load_weights`](https://keras-rl.readthedocs.io/en/latest/agents/overview/#load_weights) and [`save_weights`](https://keras-rl.readthedocs.io/en/latest/agents/overview/#save_weights).
