### ISSUE TITLE
retrieve max-move power corresponding to move

### ISSUE THREAD

**Issue by Auxowave** [hsahovic/poke-env#98]
First of all, thanks for adding doubles support! I'm working on a VGC format playing AI so this is amazing.

I have a question, is there a way to retrieve the power of a max-move? For example for a MaxDamagePlayer, how can the agent check the power of its max moves?

**Comment by hsahovic** [comment]
Hey @Auxowave,

Thanks for opening this issue! I'm glad to hear you're excited about doubles :) Be advised that support for doubles is preliminary and most of the tooling I want to implement for doubles is still missing, so things might be a bit rough around the edges.

There's no method to retrieve the power of a max-move - yet. I can implement it if it's high priority on your end.

Alternatively, you can take a look at [what I suspect is showdown's implementation](https://github.com/smogon/pokemon-showdown/blob/ec8cd25d594c02425a6e31bfa14a157650b2b5c2/sim/dex-moves.ts#L462).

**Comment by Auxowave** [comment]
Hi,

It's not high priority so no need to implement it, merely a convenience. What you're linking to in showdown's implementation is basically exactly what I'm looking for, so thanks a bunch!

**Comment by hsahovic** [comment]
Great. I'm going to add this to my longer-term to do list then :)

**Comment by hsahovic** [comment]
This is implemented in #139
